import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#F8FAFC',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  main: {
    flex: 1,
    width: '100%',
    maxWidth: '1152px',
    margin: '0 auto',
    padding: '32px 24px',
    boxSizing: 'border-box',
  },
  spaceWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
  },
  header: {
    marginBottom: '8px',
  },
  title: {
    fontSize: '28px',
    fontWeight: 900,
    letterSpacing: '0.02em',
    color: '#0B132B',
    margin: '0 0 4px 0',
    textTransform: 'uppercase',
  },
  subtitle: {
    fontSize: '12px',
    color: '#64748B',
    margin: 0,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  toastSuccess: {
    padding: '16px',
    borderRadius: '8px',
    backgroundColor: '#ECFDF5',
    border: '1px solid #A7F3D0',
    color: '#065F46',
    fontSize: '12px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  toastError: {
    padding: '16px',
    borderRadius: '8px',
    backgroundColor: '#FEF2F2',
    border: '1px solid #FECACA',
    color: '#991B1B',
    fontSize: '12px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  dropZone: {
    border: '2px dashed #CBD5E1',
    borderRadius: '16px',
    padding: '40px 24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    cursor: 'pointer',
    backgroundColor: '#FFFFFF',
    transition: 'all 0.15s ease',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
  },
  dropZoneDragging: {
    border: '2px dashed #0B132B',
    backgroundColor: '#F1F5F9',
    transform: 'scale(1.01)',
  },
  dropZoneIconWrap: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    backgroundColor: '#F1F5F9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#0B132B',
    marginBottom: '16px',
  },
  dropZoneTitle: {
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
    margin: '0 0 4px 0',
  },
  dropZoneDesc: {
    fontSize: '12px',
    color: '#64748B',
    margin: 0,
  },
  queueCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
    border: '1px solid #E2E8F0',
    overflow: 'hidden',
  },
  queueHeader: {
    padding: '16px',
    backgroundColor: '#F8FAFC',
    borderBottom: '1px solid #E2E8F0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  queueTitle: {
    fontSize: '12px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  clearAllBtn: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#DC2626',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  fileList: {
    display: 'flex',
    flexDirection: 'column',
  },
  fileItem: {
    padding: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #F1F5F9',
    transition: 'background-color 0.15s ease',
  },
  fileItemLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  fileTypeIconWrap: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    backgroundColor: '#F1F5F9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#0B132B',
  },
  fileInfoWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  fileName: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#0B132B',
    margin: 0,
  },
  fileMeta: {
    fontSize: '10px',
    color: '#64748B',
    margin: 0,
  },
  fileItemActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  actionBtn: {
    padding: '8px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#64748B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '4px',
  },
  removeBtn: {
    padding: '8px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94A3B8',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '4px',
  },
  queueFooter: {
    padding: '16px',
    backgroundColor: '#F8FAFC',
    borderTop: '1px solid #E2E8F0',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  submitBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '12px 32px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
    transition: 'background-color 0.15s ease',
  },
  submitBtnDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 50,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    maxWidth: '768px',
    width: '100%',
    padding: '16px',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '90vh',
    boxSizing: 'border-box',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '12px',
    borderBottom: '1px solid #E2E8F0',
  },
  modalTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  modalCloseBtn: {
    padding: '4px',
    color: '#64748B',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    flex: 1,
    overflow: 'auto',
    padding: '16px 0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0F172A',
    borderRadius: '6px',
    marginTop: '8px',
  },
  modalImg: {
    maxHeight: '70vh',
    objectFit: 'contain',
    borderRadius: '4px',
  },
};
