import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    width: '100%',
    maxWidth: '1152px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  batchTabsWrap: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#F1F5F9',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1px solid #E2E8F0',
  },
  batchTab: {
    padding: '8px 16px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    cursor: 'pointer',
    backgroundColor: '#FFFFFF',
    color: '#475569',
    border: '1px solid #CBD5E1',
    transition: 'all 0.15s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  batchTabActive: {
    backgroundColor: '#0B132B',
    color: '#FBBF24',
    borderColor: '#0B132B',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  batchBadge: {
    fontSize: '10px',
    fontWeight: 900,
    padding: '2px 6px',
    borderRadius: '4px',
    backgroundColor: 'rgba(251, 191, 36, 0.2)',
    color: '#D97706',
  },
  topBar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
  },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: '#0B132B',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
  },
  actionGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  editToggleBtn: {
    padding: '8px 16px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    border: '1px solid #CBD5E1',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  editToggleBtnActive: {
    backgroundColor: '#F59E0B',
    color: '#FFFFFF',
    borderColor: '#F59E0B',
  },
  saveBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '8px 24px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
  },
  saveBtnDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
  feedbackSuccess: {
    padding: '16px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#ECFDF5',
    color: '#065F46',
    border: '1px solid #A7F3D0',
  },
  feedbackError: {
    padding: '16px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#FEF2F2',
    color: '#991B1B',
    border: '1px solid #FECACA',
  },
  scoreBanner: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    borderRadius: '12px',
    padding: '24px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  scoreBannerInner: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '24px',
  },
  teamCol: {
    flex: 1,
  },
  teamColRight: {
    flex: 1,
    textAlign: 'right',
  },
  teamTag: {
    fontSize: '10px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    color: '#94A3B8',
  },
  teamName: {
    fontSize: '24px',
    fontWeight: 900,
    textTransform: 'uppercase',
    letterSpacing: '-0.02em',
    color: '#FFFFFF',
    margin: '4px 0 0 0',
  },
  teamScore: {
    fontSize: '36px',
    fontWeight: 900,
    color: '#FBBF24',
    margin: '8px 0 0 0',
  },
  vsCenter: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  vsBadge: {
    fontSize: '11px',
    fontWeight: 900,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    color: '#94A3B8',
    backgroundColor: '#1E293B',
    padding: '4px 12px',
    borderRadius: '9999px',
  },
  sportBadge: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#CBD5E1',
    marginTop: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  filterTabsWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderBottom: '1px solid #E2E8F0',
    paddingBottom: '12px',
  },
  filterTab: {
    padding: '6px 14px',
    borderRadius: '9999px',
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    cursor: 'pointer',
    backgroundColor: '#FFFFFF',
    color: '#475569',
    border: '1px solid #E2E8F0',
    transition: 'all 0.15s ease',
  },
  filterTabActive: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    borderColor: '#0B132B',
  },
  tableCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
    border: '1px solid #E2E8F0',
    overflow: 'hidden',
  },
  tableHeader: {
    padding: '16px',
    backgroundColor: '#F8FAFC',
    borderBottom: '1px solid #E2E8F0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tableTitle: {
    fontSize: '12px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  tableSubtitle: {
    fontSize: '11px',
    color: '#64748B',
  },
  tableWrap: {
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    textAlign: 'left',
    fontSize: '12px',
    borderCollapse: 'collapse',
  },
  theadRow: {
    backgroundColor: '#F1F5F9',
    borderBottom: '1px solid #E2E8F0',
    color: '#475569',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    fontSize: '10px',
  },
  th: {
    padding: '12px 16px',
  },
  thCenter: {
    padding: '12px 12px',
    textAlign: 'center',
  },
  tbodyRow: {
    borderBottom: '1px solid #F1F5F9',
    transition: 'background-color 0.1s ease',
  },
  tdNum: {
    padding: '12px 16px',
    textAlign: 'center',
    fontWeight: 700,
    color: '#64748B',
  },
  tdAthleteName: {
    padding: '12px 16px',
    fontWeight: 700,
    color: '#0B132B',
  },
  tdTeam: {
    padding: '12px 16px',
  },
  teamBadgeHome: {
    padding: '2px 10px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: 900,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    backgroundColor: '#EFF6FF',
    color: '#1D4ED8',
    border: '1px solid #BFDBFE',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  teamBadgeAway: {
    padding: '2px 10px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: 900,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    backgroundColor: '#FEF3C7',
    color: '#B45309',
    border: '1px solid #FDE68A',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  tdStat: {
    padding: '12px 12px',
    textAlign: 'center',
    fontWeight: 700,
    color: '#0B132B',
  },
  statInput: {
    width: '56px',
    textAlign: 'center',
    backgroundColor: '#FEF3C7',
    border: '1px solid #FCD34D',
    borderRadius: '4px',
    padding: '4px',
    fontSize: '12px',
    fontWeight: 700,
    color: '#0B132B',
    outline: 'none',
    boxSizing: 'border-box',
  },
  tdFgPct: {
    padding: '12px 16px',
    textAlign: 'center',
    fontWeight: 600,
    color: '#475569',
  },
  tfootRow: {
    backgroundColor: '#F1F5F9',
    borderTop: '2px solid #CBD5E1',
    fontWeight: 800,
    color: '#0B132B',
    fontSize: '12px',
  },
  tfootTdTotalLabel: {
    padding: '12px 16px',
    textAlign: 'center',
  },
  tfootTdStatHighlight: {
    padding: '12px 12px',
    textAlign: 'center',
    color: '#D97706',
  },
  tfootTdStat: {
    padding: '12px 12px',
    textAlign: 'center',
  },
  tfootTdDash: {
    padding: '12px 16px',
    textAlign: 'center',
  },
};
