import React from 'react';

const FONT_FAMILY = "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    fontFamily: FONT_FAMILY,
  },
  layoutBody: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 58px)',
    overflow: 'hidden',
    fontFamily: FONT_FAMILY,
  },
  contentArea: {
    flex: 1,
    padding: '36px 48px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    fontFamily: FONT_FAMILY,
  },
  profileCardWrapper: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '36px 40px',
    width: '100%',
    maxWidth: '860px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    boxSizing: 'border-box',
    fontFamily: FONT_FAMILY,
  },
  topSection: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    width: '100%',
  },
  topLeftGroup: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '24px',
  },
  avatarBox: {
    width: '110px',
    height: '110px',
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: '#0B132B',
  },
  nameDetailsCol: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    fontFamily: FONT_FAMILY,
  },
  officialName: {
    fontFamily: FONT_FAMILY,
    fontSize: '24px',
    fontWeight: 800,
    letterSpacing: '-0.01em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
    lineHeight: 1.15,
  },
  officialSubtitle: {
    fontFamily: FONT_FAMILY,
    fontSize: '13px',
    fontWeight: 600,
    color: '#64748B',
    margin: '4px 0 0 0',
  },
  affiliationTagBox: {
    border: '1.5px solid #0B132B',
    padding: '5px 12px',
    display: 'inline-flex',
    flexDirection: 'column',
    marginTop: '12px',
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    fontFamily: FONT_FAMILY,
  },
  affiliationLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: '8.5px',
    fontWeight: 800,
    letterSpacing: '0.1em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  affiliationValue: {
    fontFamily: FONT_FAMILY,
    fontSize: '13px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    color: '#0B132B',
    textTransform: 'uppercase',
    marginTop: '2px',
  },
  editProfileBtn: {
    fontFamily: FONT_FAMILY,
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '10px 22px',
    border: 'none',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    borderRadius: '1px',
    cursor: 'pointer',
    textTransform: 'uppercase',
    transition: 'opacity 0.15s ease',
  },
  dividerLine: {
    borderTop: '1px solid #0B132B',
    width: '100%',
    margin: '2px 0 6px 0',
  },

  /* Sections */
  sectionCard: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    border: '1px solid #0B132B',
    fontFamily: FONT_FAMILY,
  },
  sectionBannerDark: {
    fontFamily: FONT_FAMILY,
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '6px 12px',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    width: '100%',
    boxSizing: 'border-box',
  },
  sectionBannerGray: {
    fontFamily: FONT_FAMILY,
    backgroundColor: '#D1D5DB',
    color: '#0B132B',
    borderBottom: '1px solid #0B132B',
    padding: '6px 12px',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    width: '100%',
    boxSizing: 'border-box',
  },
  identifierBox: {
    fontFamily: FONT_FAMILY,
    backgroundColor: '#FFFFFF',
    padding: '12px 14px',
    fontSize: '13px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  summaryBox: {
    backgroundColor: '#FFFFFF',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: FONT_FAMILY,
  },
  summaryRow: {
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    fontFamily: FONT_FAMILY,
  },
  summaryRowBorder: {
    borderBottom: '1px solid #E2E8F0',
  },
  rowLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: '9.5px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  rowValue: {
    fontFamily: FONT_FAMILY,
    fontSize: '14px',
    fontWeight: 700,
    color: '#0B132B',
  },
};
