import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  backButton: {
    paddingRight: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  sectionLabel: {
    color: "#5C6B82",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
    marginTop: 22,
    marginBottom: 12,
    fontFamily: fontPlatform,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
    marginBottom: 16,
  },
  loadingSportsContainer: {
    paddingVertical: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E293B",
    marginBottom: 16,
  },
  loadingSportsText: {
    color: "#00D2FF",
    fontSize: 13,
    fontWeight: "600",
    fontFamily: fontPlatform,
  },
  sportTileHalf: {
    width: "48%",
    height: 110,
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  sportTileFull: {
    width: "100%",
    height: 110,
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  sportTileActive: {
    borderColor: "#00D2FF",
    backgroundColor: "#081B2E",
  },
  sportTileIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0, 210, 255, 0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  sportTileTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  sportTileTitleActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  subLabel: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
    fontFamily: fontPlatform,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111C30",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    height: 50,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: fontPlatform,
  },
  searchIcon: {
    marginLeft: 8,
  },
  athleteCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 12,
    marginBottom: 10,
  },
  avatarImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "#1E293B",
  },
  avatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "#111C30",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  avatarPlaceholderText: {
    color: "#00D2FF",
    fontWeight: "800",
    fontSize: 18,
  },
  athleteInfo: {
    flex: 1,
    marginLeft: 14,
  },
  athleteName: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    letterSpacing: 0.5,
  },
  athleteSubtitle: {
    color: "#8E9BAE",
    fontSize: 13,
    marginTop: 2,
    fontFamily: fontPlatform,
  },
  removeButton: {
    padding: 6,
  },
  addAthleteBtn: {
    height: 50,
    borderRadius: 10,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#2D3E55",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    marginBottom: 20,
  },
  addAthleteBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  formGroup: {
    marginBottom: 16,
  },
  rowGroup: {
    flexDirection: "row",
    gap: 12,
  },
  halfFormGroup: {
    flex: 1,
    marginBottom: 16,
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111C30",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    height: 50,
  },
  inputText: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: fontPlatform,
  },
  startLoggingBtn: {
    height: 54,
    borderRadius: 12,
    backgroundColor: "#091325",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#1E3A5F",
  },
  startLoggingBtnText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#0E172A",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "75%",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  poolItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111C30",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  poolItemTitle: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
  },
  poolItemSub: {
    color: "#8E9BAE",
    fontSize: 12,
    marginTop: 2,
  },
  inputBoxError: {
    borderColor: "#EF4444",
    borderWidth: 1.5,
    backgroundColor: "#1C0D19",
  },
  errorText: {
    color: "#EF4444",
    fontSize: 12,
    marginTop: 4,
    fontFamily: fontPlatform,
  },
  interruptionOverlay: {
    flex: 1,
    backgroundColor: "rgba(3, 7, 18, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  interruptionCard: {
    width: "100%",
    backgroundColor: "#0E172A",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#EF4444",
    padding: 22,
    alignItems: "center",
  },
  interruptionIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  interruptionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
    marginBottom: 8,
    textAlign: "center",
  },
  interruptionSubtitle: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 20,
  },
  interruptionBox: {
    width: "100%",
    backgroundColor: "#111C30",
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    marginBottom: 20,
  },
  interruptionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 4,
  },
  interruptionItemText: {
    color: "#F87171",
    fontSize: 13.5,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  interruptionBtn: {
    width: "100%",
    height: 50,
    borderRadius: 10,
    backgroundColor: "#EF4444",
    justifyContent: "center",
    alignItems: "center",
  },
  interruptionBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  // Success Session Started Modal Styles
  successCard: {
    width: "100%",
    backgroundColor: "#0E172A",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#00D2FF",
    padding: 22,
    alignItems: "center",
  },
  successIconCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "rgba(0, 210, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 4,
  },
  summaryLabelText: {
    color: "#8E9BAE",
    fontSize: 13,
    fontFamily: fontPlatform,
  },
  summaryValueText: {
    color: "#FFFFFF",
    fontSize: 13.5,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  successBtn: {
    width: "100%",
    height: 50,
    borderRadius: 10,
    backgroundColor: "#00D2FF",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  successBtnText: {
    color: "#070D19",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  // Date & Time Picker Button Styles
  pickerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#111C30",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    height: 50,
  },
  pickerContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 6,
  },
  pickerText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
    fontFamily: fontPlatform,
  },
  pickerTextPlaceholder: {
    color: "#5C6B82",
    fontWeight: "400",
  },
  searchMapLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "rgba(0, 200, 255, 0.1)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.25)",
  },
  searchMapLinkText: {
    color: "#00C8FF",
    fontSize: 11,
    fontWeight: "700",
  },
  mapBadge: {
    backgroundColor: "rgba(0, 200, 255, 0.15)",
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.3)",
  },
  mapBadgeText: {
    color: "#00C8FF",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  // Modal Sheet & Header Styles
  pickerModalSheet: {
    backgroundColor: "#0E172A",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "85%",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  pickerModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  pickerModalTitleBox: {
    flex: 1,
  },
  pickerModalTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0.8,
    fontFamily: fontBoldPlatform,
  },
  pickerModalSubtitle: {
    color: "#00C8FF",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
  },
  quickChipsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  quickChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "#111C30",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  quickChipActive: {
    backgroundColor: "rgba(0, 200, 255, 0.15)",
    borderColor: "#00C8FF",
  },
  quickChipText: {
    color: "#8E9BAE",
    fontSize: 12,
    fontWeight: "700",
  },
  quickChipTextActive: {
    color: "#00C8FF",
    fontWeight: "800",
  },
  // Calendar Styles
  calendarMonthNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    paddingHorizontal: 4,
  },
  monthNavBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#111C30",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  calendarMonthTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  weekDaysHeader: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 8,
  },
  weekDayColText: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "800",
    width: 38,
    textAlign: "center",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
    rowGap: 8,
  },
  dayCell: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
  },
  dayCellEmpty: {
    width: 38,
    height: 38,
  },
  dayCellActive: {
    backgroundColor: "#00C8FF",
  },
  dayCellToday: {
    borderWidth: 1.5,
    borderColor: "#00C8FF",
  },
  dayCellText: {
    color: "#E2E8F0",
    fontSize: 14,
    fontWeight: "600",
  },
  dayCellTextActive: {
    color: "#070D19",
    fontWeight: "900",
  },
  // Time Clock Display Styles
  clockHeroCard: {
    backgroundColor: "#111C30",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.2)",
  },
  clockHeroDigitsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  clockDigitBox: {
    backgroundColor: "#070D19",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  clockDigitText: {
    color: "#00C8FF",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 1,
  },
  clockColonText: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
  },
  clockAmPmToggle: {
    flexDirection: "row",
    backgroundColor: "#070D19",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 3,
    marginLeft: 6,
  },
  ampmPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  ampmPillActive: {
    backgroundColor: "#00C8FF",
  },
  ampmPillText: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "800",
  },
  ampmPillTextActive: {
    color: "#070D19",
    fontWeight: "900",
  },
  timePickerSubLabel: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    marginTop: 10,
    marginBottom: 8,
  },
  timePickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  timeGridPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#111C30",
    borderWidth: 1,
    borderColor: "#1E293B",
    minWidth: 46,
    alignItems: "center",
  },
  timeGridPillActive: {
    backgroundColor: "#00C8FF",
    borderColor: "#00C8FF",
  },
  timeGridPillText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  timeGridPillTextActive: {
    color: "#070D19",
    fontWeight: "900",
  },
  modalConfirmBtn: {
    backgroundColor: "#00C8FF",
    height: 48,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },
  modalConfirmBtnText: {
    color: "#070D19",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  // Location List Styles
  venueResultItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "#111C30",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  venueIconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "rgba(0, 200, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  venueDetails: {
    flex: 1,
  },
  venueNameText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  venueAddressText: {
    color: "#8E9BAE",
    fontSize: 12,
    marginTop: 2,
  },
  venueCategoryBadge: {
    color: "#00C8FF",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  customVenuePickBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(0, 200, 255, 0.12)",
    borderWidth: 1,
    borderColor: "#00C8FF",
    padding: 12,
    borderRadius: 10,
    marginBottom: 12,
  },
  customVenuePickText: {
    color: "#00C8FF",
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
});

export default styles;
