import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  brandTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  closeHeaderBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#1E293B",
    backgroundColor: "#0E172A",
    justifyContent: "center",
    alignItems: "center",
  },
  sportBanner: {
    alignItems: "center",
    marginVertical: 18,
  },
  sportTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 2.5,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 230,
  },
  playerCard: {
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#1E293B",
    padding: 16,
    marginBottom: 12,
    position: "relative",
  },
  playerCardSelected: {
    borderStyle: "dashed",
    borderColor: "#00D2FF",
    backgroundColor: "#091E33",
  },
  playerCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  jerseyNumber: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  chevronIcon: {
    padding: 2,
  },
  benchBadge: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: "#0E172A",
    borderWidth: 1.5,
    borderColor: "#00D2FF",
    justifyContent: "center",
    alignItems: "center",
  },
  benchBadgeText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  lastName: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1,
    marginTop: 4,
    marginBottom: 8,
    fontFamily: fontBoldPlatform,
  },
  statsSummary: {
    color: "#8E9BAE",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  moreActionsBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 210, 255, 0.3)",
  },
  quickActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    gap: 6,
  },
  quickActionBtn: {
    flex: 1,
    backgroundColor: "#1E293B",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 210, 255, 0.3)",
  },
  quickActionBtnText: {
    color: "#00D2FF",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  // Modal correction section
  modalSectionTitle: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    marginTop: 16,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  correctionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  correctionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: "#1E293B",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.4)",
  },
  correctionBtnText: {
    color: "#EF4444",
    fontSize: 12,
    fontWeight: "800",
  },
  // Bench Rail
  benchRailContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#091224",
    borderTopWidth: 1,
    borderTopColor: "#1E293B",
    paddingTop: 12,
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  benchHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  benchTitle: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  benchListScroll: {
    gap: 12,
  },
  benchTileWrapper: {
    alignItems: "center",
    width: 60,
  },
  benchTile: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: "#0E172A",
    borderWidth: 1.5,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  benchTileActive: {
    borderColor: "#00D2FF",
    backgroundColor: "#0C2338",
  },
  benchJerseyText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  benchNameText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textAlign: "center",
    fontFamily: fontBoldPlatform,
  },
  // Floating Action Button for Save
  floatingSaveBtn: {
    position: "absolute",
    right: 20,
    bottom: 165,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 8,
  },
  // Action Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#070D19",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderColor: "#1E293B",
    padding: 20,
    paddingBottom: 36,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
    paddingBottom: 14,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  actionTile: {
    width: "48%",
    height: 105,
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  actionTileText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
