import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  backButton: {
    paddingRight: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  sectionLabel: {
    color: "#5C6B82",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
    marginTop: 22,
    marginBottom: 12,
    fontFamily: fontPlatform,
  },
  gridContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sportTileHalf: {
    width: "48%",
    height: 110,
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  sportTileFull: {
    width: "100%",
    height: 110,
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  sportTileActive: {
    borderColor: "#00D2FF",
    backgroundColor: "#081B2E",
  },
  sportTileIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0, 210, 255, 0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  sportTileTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  sportTileTitleActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  subLabel: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
    fontFamily: fontPlatform,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111C30",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    height: 50,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: fontPlatform,
  },
  searchIcon: {
    marginLeft: 8,
  },
  athleteCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0E172A",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 12,
    marginBottom: 10,
  },
  avatarImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "#1E293B",
  },
  avatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "#111C30",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  avatarPlaceholderText: {
    color: "#00D2FF",
    fontWeight: "800",
    fontSize: 18,
  },
  athleteInfo: {
    flex: 1,
    marginLeft: 14,
  },
  athleteName: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    letterSpacing: 0.5,
  },
  athleteSubtitle: {
    color: "#8E9BAE",
    fontSize: 13,
    marginTop: 2,
    fontFamily: fontPlatform,
  },
  removeButton: {
    padding: 6,
  },
  addAthleteBtn: {
    height: 50,
    borderRadius: 10,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#2D3E55",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    marginBottom: 20,
  },
  addAthleteBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  formGroup: {
    marginBottom: 16,
  },
  rowGroup: {
    flexDirection: "row",
    gap: 12,
  },
  halfFormGroup: {
    flex: 1,
    marginBottom: 16,
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111C30",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    height: 50,
  },
  inputText: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: fontPlatform,
  },
  startLoggingBtn: {
    height: 54,
    borderRadius: 12,
    backgroundColor: "#091325",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#1E3A5F",
  },
  startLoggingBtnText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#0E172A",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "75%",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  poolItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111C30",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  poolItemTitle: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
  },
  poolItemSub: {
    color: "#8E9BAE",
    fontSize: 12,
    marginTop: 2,
  },
  inputBoxError: {
    borderColor: "#EF4444",
    borderWidth: 1.5,
    backgroundColor: "#1C0D19",
  },
  errorText: {
    color: "#EF4444",
    fontSize: 12,
    marginTop: 4,
    fontFamily: fontPlatform,
  },
  interruptionOverlay: {
    flex: 1,
    backgroundColor: "rgba(3, 7, 18, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  interruptionCard: {
    width: "100%",
    backgroundColor: "#0E172A",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#EF4444",
    padding: 22,
    alignItems: "center",
  },
  interruptionIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  interruptionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
    marginBottom: 8,
    textAlign: "center",
  },
  interruptionSubtitle: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 20,
  },
  interruptionBox: {
    width: "100%",
    backgroundColor: "#111C30",
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    marginBottom: 20,
  },
  interruptionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 4,
  },
  interruptionItemText: {
    color: "#F87171",
    fontSize: 13.5,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  interruptionBtn: {
    width: "100%",
    height: 50,
    borderRadius: 10,
    backgroundColor: "#EF4444",
    justifyContent: "center",
    alignItems: "center",
  },
  interruptionBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  // Success Session Started Modal Styles
  successCard: {
    width: "100%",
    backgroundColor: "#0E172A",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#00D2FF",
    padding: 22,
    alignItems: "center",
  },
  successIconCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "rgba(0, 210, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 4,
  },
  summaryLabelText: {
    color: "#8E9BAE",
    fontSize: 13,
    fontFamily: fontPlatform,
  },
  summaryValueText: {
    color: "#FFFFFF",
    fontSize: 13.5,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  successBtn: {
    width: "100%",
    height: 50,
    borderRadius: 10,
    backgroundColor: "#00D2FF",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  successBtnText: {
    color: "#070D19",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
