import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  backButton: {
    paddingRight: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  fieldGroup: {
    marginTop: 16,
  },
  fieldLabel: {
    color: "#8E9BAE",
    fontSize: 13.5,
    fontWeight: "600",
    marginBottom: 8,
    fontFamily: fontPlatform,
  },
  inputBox: {
    backgroundColor: "#111C30",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    height: 48,
    justifyContent: "center",
  },
  inputText: {
    color: "#FFFFFF",
    fontSize: 14.5,
    fontFamily: fontPlatform,
  },
  dropdownBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#111C30",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    height: 48,
  },
  dropdownText: {
    color: "#FFFFFF",
    fontSize: 14.5,
    fontFamily: fontPlatform,
  },
  notesInput: {
    backgroundColor: "#111C30",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    paddingVertical: 12,
    height: 100,
    color: "#FFFFFF",
    fontSize: 14,
    textAlignVertical: "top",
    fontFamily: fontPlatform,
  },
  // White Player Statistics Card Container
  statsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 18,
    marginTop: 24,
    marginBottom: 20,
  },
  statsTitle: {
    color: "#000000",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  statsHeaderBlock: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  scrollHintText: {
    color: "#64748B",
    fontSize: 11.5,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#F1F5F9",
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginBottom: 4,
    minWidth: 520,
  },
  tableColPlayerHeader: {
    width: 130,
    color: "#475569",
    fontSize: 11,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  tableColHeader: {
    width: 55,
    color: "#475569",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
    fontFamily: fontBoldPlatform,
  },
  tableDataRow: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    alignItems: "center",
    minWidth: 520,
  },
  tableColPlayer: {
    width: 130,
    color: "#0F172A",
    fontSize: 13.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  tableColText: {
    width: 55,
    color: "#334155",
    fontSize: 13.5,
    fontWeight: "700",
    textAlign: "center",
    fontFamily: fontPlatform,
  },
  saveBtn: {
    height: 52,
    borderRadius: 12,
    backgroundColor: "#2563EB",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  saveBtnText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  // Modal Picker Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  pickerContainer: {
    backgroundColor: "#0E172A",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  pickerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  pickerTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  pickerOption: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: "#111C30",
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  pickerOptionSelected: {
    borderColor: "#2563EB",
    backgroundColor: "#1D3B7A",
  },
  pickerOptionText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  // Green Discard Interruption Modal Styles
  centerModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  discardCard: {
    width: "100%",
    backgroundColor: "#22C55E",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
  },
  discardTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    marginTop: 14,
    marginBottom: 12,
    textAlign: "center",
    fontFamily: fontBoldPlatform,
  },
  discardSubtitle: {
    color: "#FFFFFF",
    fontSize: 14.5,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 8,
    fontFamily: fontPlatform,
  },
  discardPillBtn: {
    width: "100%",
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  discardPillBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  // Custom Save Match Success Modal Styles
  successCard: {
    width: "100%",
    backgroundColor: "#0E172A",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 24,
    alignItems: "center",
  },
  successBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#0C2338",
    borderWidth: 1.5,
    borderColor: "#00D2FF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  successTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 8,
    fontFamily: fontBoldPlatform,
  },
  successSubtitle: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
    fontFamily: fontPlatform,
  },
  doneBtn: {
    width: "100%",
    height: 48,
    borderRadius: 10,
    backgroundColor: "#2563EB",
    justifyContent: "center",
    alignItems: "center",
  },
  doneBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
