import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  brandTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  closeHeaderBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#1E293B",
    backgroundColor: "#0E172A",
    justifyContent: "center",
    alignItems: "center",
  },
  sportBanner: {
    alignItems: "center",
    marginVertical: 18,
  },
  sportTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 2.5,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  playerCard: {
    backgroundColor: "#0E172A",
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#1E293B",
    padding: 18,
    marginBottom: 14,
  },
  playerCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  jerseyNumber: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  chevronIcon: {
    padding: 2,
  },
  lastName: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1,
    marginTop: 4,
    marginBottom: 4,
    fontFamily: fontBoldPlatform,
  },
  eventSubtitle: {
    color: "#5C6B82",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontBoldPlatform,
  },
  liveTimerDisplay: {
    color: "#00D2FF",
    fontSize: 13.5,
    fontWeight: "800",
    marginTop: 4,
    fontFamily: fontBoldPlatform,
  },
  floatingSaveBtn: {
    position: "absolute",
    right: 20,
    bottom: 40,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 8,
  },
  // Swimming Action White Bottom Sheet Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 36,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingBottom: 14,
  },
  modalTitle: {
    color: "#0B1528",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  actionBox: {
    width: "48%",
    height: 165,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#0B1528",
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBoxActive: {
    borderColor: "#00D2FF",
    backgroundColor: "#F0F9FF",
  },
  actionBoxHeader: {
    alignItems: "center",
    marginBottom: 4,
  },
  actionBoxLabel: {
    color: "#0B1528",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: 4,
    fontFamily: fontBoldPlatform,
  },
  stopwatchText: {
    color: "#0B1528",
    fontSize: 19,
    fontWeight: "900",
    marginVertical: 6,
    fontFamily: fontBoldPlatform,
  },
  timerControlRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  playCircleBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#0B1528",
    justifyContent: "center",
    alignItems: "center",
  },
  retryCircleBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#F1F5F9",
    borderWidth: 1.5,
    borderColor: "#0B1528",
    justifyContent: "center",
    alignItems: "center",
  },
  distanceInputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#0B1528",
    borderRadius: 4,
    paddingHorizontal: 12,
    height: 36,
    width: "100%",
    marginVertical: 8,
  },
  distanceInput: {
    flex: 1,
    color: "#0B1528",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    fontFamily: fontBoldPlatform,
  },
  distanceUnit: {
    color: "#0B1528",
    fontSize: 15,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  saveMiniBtn: {
    width: "100%",
    height: 32,
    backgroundColor: "#0B1528",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  saveMiniBtnText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  splitListBadge: {
    marginTop: 6,
    color: "#059669",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
    fontFamily: fontPlatform,
  },
});

export default styles;
