import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#080F21",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 36,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  sectionHeadingContainer: {},
  mainTitle: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  activeUnderline: {
    width: 42,
    height: 3,
    backgroundColor: "#38BDF8",
    borderRadius: 2,
    marginTop: 6,
  },
  headerEditButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
  },
  headerEditButtonInactive: {
    borderColor: "#38BDF8",
    backgroundColor: "#10233D",
  },
  headerEditButtonActive: {
    borderColor: "#FF4D4D",
    backgroundColor: "#33141E",
  },
  headerEditButtonText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  editingBanner: {
    backgroundColor: "#38BDF8",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  editingBannerText: {
    color: "#080F21",
    fontSize: 12,
    fontWeight: "800",
  },
  profileMainCard: {
    backgroundColor: "#111C35",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#1E2C4A",
    marginBottom: 20,
  },
  avatarContainer: {
    alignItems: "center",
    marginVertical: 12,
  },
  avatarBox: {
    width: 100,
    height: 100,
    borderRadius: 20,
    backgroundColor: "#1C2943",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  avatarImage: {
    width: 50,
    height: 50,
    tintColor: "#FFFFFF",
  },
  cameraBadge: {
    position: "absolute",
    bottom: -6,
    right: -6,
    backgroundColor: "#38BDF8",
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#111C35",
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  inputWrapper: {
    backgroundColor: "#16233E",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#223354",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  inputWrapperEditable: {
    borderColor: "#38BDF8",
    backgroundColor: "#152844",
  },
  textInput: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    padding: 0,
    flex: 1,
  },
  rowTwoFields: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  dropdownWrapper: {
    backgroundColor: "#16233E",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#223354",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  physicalStatsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 14,
  },
  cyanAccentBar: {
    width: 3,
    height: 16,
    backgroundColor: "#38BDF8",
    borderRadius: 2,
    marginRight: 8,
  },
  physicalStatsTitle: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  horizontalDivider: {
    flex: 1,
    height: 1,
    backgroundColor: "#203050",
    marginLeft: 12,
  },
  statsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 18,
  },
  statBox: {
    flex: 1,
    backgroundColor: "#16233E",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#223354",
  },
  statBoxEditable: {
    borderColor: "#38BDF8",
    backgroundColor: "#152844",
  },
  statBoxLabel: {
    color: "#38BDF8",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  statBoxValueRow: {
    flexDirection: "row",
    alignItems: "baseline",
    marginTop: 6,
  },
  statBoxValueInput: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    padding: 0,
    minWidth: 40,
  },
  statBoxUnit: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    marginLeft: 4,
  },
  drawerContainer: {
    backgroundColor: "#0C152B",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1B2A48",
    padding: 12,
    marginBottom: 18,
  },
  drawerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  drawerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  drawerTitleText: {
    color: "#38BDF8",
    fontSize: 12,
    fontWeight: "800",
  },
  drawerContent: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#1B2A48",
    gap: 12,
  },
  calculatedItem: {
    gap: 2,
  },
  calcLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "700",
  },
  calcValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  calcUnit: {
    color: "#38BDF8",
    fontSize: 12,
    fontWeight: "700",
  },
  calcFormula: {
    color: "#64748B",
    fontSize: 10,
    fontStyle: "italic",
  },
  affiliationSection: {
    marginBottom: 20,
  },
  affiliationCard: {
    backgroundColor: "#0B1327",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#1B2A48",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  affiliationLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  shieldIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#162441",
    justifyContent: "center",
    alignItems: "center",
  },
  affiliationTextGroup: {
    marginLeft: 12,
    flex: 1,
  },
  teamNameText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  sportTagText: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  verifiedBadge: {
    marginLeft: 8,
  },
  documentsHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  addDocButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#16233E",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#223354",
  },
  addDocButtonText: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
  },
  documentsSubtitleText: {
    color: "#64748B",
    fontSize: 11,
    flex: 1,
    marginRight: 8,
  },
  documentsCardList: {
    gap: 10,
  },
  documentItemCard: {
    backgroundColor: "#0B1327",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#1B2A48",
  },
  docHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  docTitleGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  docTitleInput: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    padding: 0,
    flex: 1,
  },
  deleteDocButton: {
    padding: 4,
    marginLeft: 8,
  },
  docFileDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#15223A",
  },
  docFileMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    marginRight: 8,
  },
  docFileNameText: {
    color: "#CBD5E1",
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 140,
  },
  docUploadedAtText: {
    color: "#64748B",
    fontSize: 10,
  },
  docNoFileText: {
    color: "#64748B",
    fontSize: 11,
    fontStyle: "italic",
    flex: 1,
  },
  uploadDocActionButton: {
    backgroundColor: "#162540",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#25385C",
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  uploadDocActionButtonText: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
  },
  modalFieldGroup: {
    marginBottom: 16,
  },
  filePickerBox: {
    backgroundColor: "#16233E",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#223354",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  filePickerTextGroup: {
    flex: 1,
  },
  filePickerMainText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  filePickerSubText: {
    color: "#64748B",
    fontSize: 11,
    marginTop: 2,
  },
  modalErrorText: {
    color: "#FF4D4D",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 12,
  },
  modalActionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
  },
  modalSaveButton: {
    flex: 1,
    backgroundColor: "#38BDF8",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  modalSaveButtonText: {
    color: "#080F21",
    fontSize: 14,
    fontWeight: "900",
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#64748B",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  modalCancelButtonText: {
    color: "#94A3B8",
    fontSize: 14,
    fontWeight: "800",
  },
  successToast: {
    backgroundColor: "#38BDF8",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  successToastText: {
    color: "#080F21",
    fontSize: 13,
    fontWeight: "800",
  },
  updatePasswordButton: {
    backgroundColor: "#38BDF8",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 4,
  },
  updatePasswordButtonText: {
    color: "#080F21",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  actionButtonsGroup: {
    gap: 12,
    marginTop: 8,
  },
  updateButton: {
    backgroundColor: "#38BDF8",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    shadowColor: "#38BDF8",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  updateButtonText: {
    color: "#080F21",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  cancelButton: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#64748B",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#94A3B8",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  logoutButton: {
    backgroundColor: "#FF4D4D",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  logoutButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  logoutConfirmButton: {
    flex: 1,
    backgroundColor: "#FF4D4D",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  logoutConfirmButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(4, 9, 20, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#111C35",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#1E2C4A",
    padding: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  modalSubtitle: {
    color: "#94A3B8",
    fontSize: 12,
    marginTop: 4,
    marginBottom: 16,
  },
  categoryListGroup: {
    gap: 10,
    marginBottom: 18,
  },
  categoryOptionCard: {
    backgroundColor: "#16233E",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "#223354",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  categoryOptionCardSelected: {
    borderColor: "#38BDF8",
    backgroundColor: "#152844",
  },
  categoryOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  categoryOptionText: {
    color: "#94A3B8",
    fontSize: 14,
    fontWeight: "800",
  },
  categoryOptionTextSelected: {
    color: "#FFFFFF",
  },
  modalCloseButton: {
    backgroundColor: "#38BDF8",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  modalCloseButtonText: {
    color: "#080F21",
    fontSize: 14,
    fontWeight: "900",
  },
  skeletonPill: {
    backgroundColor: "#16233E",
    borderRadius: 8,
    marginBottom: 16,
  },
  calendarNavRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  calendarNavBtn: {
    backgroundColor: "#16233E",
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#223354",
  },
  calendarNavTitleGroup: {
    flexDirection: "row",
    gap: 8,
  },
  calendarSelectorPill: {
    backgroundColor: "#16233E",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#223354",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  calendarSelectorPillActive: {
    borderColor: "#38BDF8",
    backgroundColor: "#152844",
  },
  calendarSelectorText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  calendarGridContainer: {
    marginBottom: 16,
  },
  calendarWeekRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  calendarWeekText: {
    color: "#38BDF8",
    fontSize: 12,
    fontWeight: "800",
    width: "14%",
    textAlign: "center",
  },
  calendarDaysGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calendarDayCell: {
    width: "14%",
    height: 38,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    marginVertical: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: "#38BDF8",
  },
  calendarDayText: {
    color: "#CBD5E1",
    fontSize: 13,
    fontWeight: "700",
  },
  calendarDayTextSelected: {
    color: "#080F21",
    fontWeight: "900",
  },
  calendarMonthsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  calendarMonthItem: {
    width: "30%",
    backgroundColor: "#16233E",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#223354",
  },
  calendarMonthItemSelected: {
    borderColor: "#38BDF8",
    backgroundColor: "#152844",
  },
  calendarMonthText: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "800",
  },
  calendarMonthTextSelected: {
    color: "#38BDF8",
  },
  calendarYearsScrollView: {
    maxHeight: 200,
    marginBottom: 16,
  },
  calendarYearsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  calendarYearItem: {
    width: "30%",
    backgroundColor: "#16233E",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#223354",
  },
  calendarYearItemSelected: {
    borderColor: "#38BDF8",
    backgroundColor: "#152844",
  },
  calendarYearText: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "800",
  },
  calendarYearTextSelected: {
    color: "#38BDF8",
  },

  /* WORKLOAD ANALYTICS STYLES */
  workloadAcwrCard: {
    backgroundColor: "#0D1B2A",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  workloadAcwrHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  workloadSubLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  workloadAcwrValue: {
    color: "#FFFFFF",
    fontSize: 32,
    fontWeight: "900",
    marginTop: 2,
  },
  workloadStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  workloadStatusText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  workloadDescText: {
    color: "#CBD5E1",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
    marginBottom: 14,
  },
  loadComparisonRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111C35",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  loadBoxLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "800",
  },
  loadBoxValue: {
    color: "#38BDF8",
    fontSize: 16,
    fontWeight: "900",
    marginTop: 2,
  },
  loadVerticalDivider: {
    width: 1,
    height: 28,
    backgroundColor: "#1E293B",
  },
  weeklyLogSection: {
    marginTop: 6,
  },
  weeklyLogHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  weeklyLogTitle: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  coachBadgeTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#111C35",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  coachBadgeText: {
    color: "#38BDF8",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  dailyLogsScrollContent: {
    flexDirection: "row",
    gap: 8,
    paddingVertical: 4,
  },
  dailyLogCard: {
    width: 76,
    backgroundColor: "#0D1B2A",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  dailyLogDate: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 4,
  },
  dailyLogDuration: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 4,
  },
  srpeTag: {
    backgroundColor: "#1E293B",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 4,
  },
  srpeTagText: {
    color: "#38BDF8",
    fontSize: 10,
    fontWeight: "800",
  },
  dailyLoadText: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "700",
  },
});

export default styles;
