import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  layout: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 64px)',
    overflow: 'hidden',
  },
  main: {
    flex: 1,
    padding: '36px 48px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    height: '100%',
    boxSizing: 'border-box',
  },
  topNavRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '20px',
  },
  breadcrumbBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: 'none',
    border: 'none',
    color: '#64748B',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    cursor: 'pointer',
    padding: 0,
    textTransform: 'uppercase',
  },
  titleRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '28px',
  },
  pageTitle: {
    fontSize: '34px',
    fontWeight: 900,
    letterSpacing: '-0.03em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
    lineHeight: 1.1,
  },
  primaryActionBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '12px 20px',
    border: 'none',
    borderRadius: '2px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  // Two-Column Grid
  workspaceGrid: {
    display: 'grid',
    gridTemplateColumns: '320px 1fr',
    gap: '24px',
    alignItems: 'start',
  },
  // Left Column Card
  leftPanelCard: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #CBD5E1',
    borderRadius: '2px',
    padding: '24px',
    boxSizing: 'border-box',
  },
  leftPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '24px',
    color: '#0B132B',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  fieldGroup: {
    marginBottom: '20px',
  },
  fieldLabel: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    color: '#64748B',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    marginBottom: '8px',
  },
  textInput: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1.5px solid #CBD5E1',
    borderRadius: '2px',
    padding: '12px 14px',
    fontSize: '13px',
    fontFamily: 'monospace',
    fontWeight: 700,
    color: '#0B132B',
    textTransform: 'uppercase',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    transition: 'border-color 0.15s ease',
  },
  // Right Column Builder Panel
  rightPanelCard: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #CBD5E1',
    borderRadius: '2px',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  rightPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 24px',
    borderBottom: '1.5px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
  },
  rightPanelHeaderTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '12px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  metricCountBadge: {
    fontFamily: 'monospace',
    fontSize: '11px',
    fontWeight: 700,
    color: '#64748B',
    letterSpacing: '0.05em',
  },
  // Metric Rows Container
  metricCardsList: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  metricRowBox: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #CBD5E1',
    borderRadius: '2px',
    padding: '24px',
    boxSizing: 'border-box',
    position: 'relative',
  },
  metricFormRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px',
    alignItems: 'start',
  },
  selectDropdown: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1.5px solid #CBD5E1',
    borderRadius: '2px',
    padding: '12px 38px 12px 14px',
    fontSize: '12px',
    fontWeight: 700,
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    cursor: 'pointer',
    appearance: 'none',
    WebkitAppearance: 'none',
    MozAppearance: 'none',
    textTransform: 'uppercase',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
  },
  selectWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    width: '100%',
  },
  selectChevron: {
    position: 'absolute',
    right: '12px',
    pointerEvents: 'none',
    color: '#0B132B',
    width: 18,
    height: 18,
    zIndex: 2,
  },
  removeStatBtn: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    background: 'none',
    border: 'none',
    color: '#DC2626',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '2px',
    transition: 'all 0.15s ease',
  },
  // Template Picker Styles
  templateBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '20px',
    padding: '14px 18px',
    backgroundColor: '#F8FAFC',
    border: '1.5px solid #E2E8F0',
    borderRadius: '2px',
  },
  templateLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#475569',
    textTransform: 'uppercase',
    marginRight: '6px',
  },
  templatePill: {
    padding: '6px 12px',
    fontSize: '11px',
    fontWeight: 700,
    borderRadius: '2px',
    border: '1px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  templatePillActive: {
    padding: '6px 12px',
    fontSize: '11px',
    fontWeight: 800,
    borderRadius: '2px',
    border: '1px solid #0B132B',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    cursor: 'pointer',
  },
  // Calculation Switcher & Chips
  calcToggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '14px',
    paddingTop: '12px',
    borderTop: '1px dashed #E2E8F0',
  },
  toggleBtnGroup: {
    display: 'inline-flex',
    borderRadius: '2px',
    border: '1px solid #CBD5E1',
    overflow: 'hidden',
  },
  toggleOptionBtn: {
    padding: '6px 12px',
    fontSize: '11px',
    fontWeight: 700,
    border: 'none',
    backgroundColor: '#FFFFFF',
    color: '#64748B',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  toggleOptionBtnActive: {
    padding: '6px 12px',
    fontSize: '11px',
    fontWeight: 800,
    border: 'none',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    cursor: 'pointer',
  },
  formulaHelperBox: {
    marginTop: '12px',
    padding: '14px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '2px',
  },
  chipList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '6px',
    marginBottom: '10px',
  },
  variableChip: {
    padding: '3px 8px',
    fontSize: '11px',
    fontFamily: 'monospace',
    fontWeight: 700,
    backgroundColor: '#FFFFFF',
    border: '1px solid #CBD5E1',
    borderRadius: '2px',
    color: '#0B132B',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  formulaPresetBtn: {
    padding: '4px 8px',
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: '#E2E8F0',
    border: 'none',
    borderRadius: '2px',
    color: '#334155',
    cursor: 'pointer',
    marginRight: '6px',
    marginBottom: '4px',
  },
  // Add Metric Button (Dashed)
  addMetricDashedBtn: {
    width: '100%',
    border: '2px dashed #CBD5E1',
    borderRadius: '2px',
    backgroundColor: '#FFFFFF',
    padding: '24px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxSizing: 'border-box',
    transition: 'all 0.15s ease',
  },
  plusSquareIcon: {
    width: '28px',
    height: '28px',
    border: '1.5px solid #64748B',
    borderRadius: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#0B132B',
    marginBottom: '8px',
  },
  addMetricText: {
    fontSize: '11px',
    fontWeight: 800,
    color: '#334155',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  // Panel Footer & Actions
  panelFooter: {
    backgroundColor: '#E2E8F0',
    borderTop: '1.5px solid #CBD5E1',
    padding: '24px 24px',
    boxSizing: 'border-box',
  },
  footerNoticeText: {
    fontSize: '12px',
    fontStyle: 'italic',
    color: '#475569',
    textAlign: 'center',
    margin: '0 0 16px 0',
  },
  submitBtn: {
    width: '100%',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '2px',
    padding: '16px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    fontSize: '12px',
    fontWeight: 900,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  // Catalog Table Styles
  catalogTableBox: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #0B132B',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    backgroundColor: '#F8FAFC',
    padding: '14px 18px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#0B132B',
    borderBottom: '1.5px solid #0B132B',
    borderRight: '1.5px solid #E2E8F0',
    textTransform: 'uppercase',
  },
  td: {
    padding: '16px 18px',
    fontSize: '13px',
    borderBottom: '1px solid #E2E8F0',
    borderRight: '1px solid #E2E8F0',
    color: '#0B132B',
  },
  activeBadge: {
    display: 'inline-block',
    padding: '4px 8px',
    backgroundColor: '#DCFCE7',
    color: '#166534',
    borderRadius: '2px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
  },
  statTag: {
    display: 'inline-block',
    padding: '3px 8px',
    backgroundColor: '#F1F5F9',
    color: '#334155',
    borderRadius: '2px',
    fontSize: '11px',
    fontFamily: 'monospace',
    fontWeight: 700,
    marginRight: '6px',
    marginBottom: '4px',
    border: '1px solid #E2E8F0',
  },
  actionBtnOutline: {
    backgroundColor: 'transparent',
    border: '1.5px solid #0B132B',
    color: '#0B132B',
    padding: '6px 14px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    borderRadius: '2px',
    cursor: 'pointer',
    textTransform: 'uppercase',
  },
};

