import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  fixedHeaderContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: "#070D19",
    paddingHorizontal: 20,
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  brandTitle: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconCircleButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  profileCircleButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  headerDivider: {
    height: 1,
    backgroundColor: "#1E293B",
    marginBottom: 0,
  },
  greetingSection: {
    marginTop: 0,
    marginBottom: 24,
  },
  greetingTitle: {
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "800",
    letterSpacing: -0.5,
    fontFamily: fontBoldPlatform,
    marginBottom: 6,
  },
  greetingSubtitle: {
    color: "#8E9BAE",
    fontSize: 15.5,
    lineHeight: 22,
    fontFamily: fontPlatform,
  },
  filterContainer: {
    marginBottom: 26,
  },
  filterLabel: {
    color: "#5C6B82",
    fontSize: 12.5,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
    marginBottom: 12,
  },
  pillsScroll: {
    gap: 10,
  },
  pillButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
  },
  pillInactive: {
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  pillActive: {
    backgroundColor: "#00C8FF",
  },
  pillText: {
    fontSize: 13.5,
    fontWeight: "800",
    letterSpacing: 0.6,
    fontFamily: fontBoldPlatform,
  },
  pillTextInactive: {
    color: "#FFFFFF",
  },
  pillTextActive: {
    color: "#070D19",
  },
  playersSection: {
    marginBottom: 26,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  sectionTitle: {
    color: "#5C6B82",
    fontSize: 12.5,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
  },
  viewAllText: {
    color: "#00C8FF",
    fontSize: 14.5,
    fontWeight: "700",
    textDecorationLine: "underline",
    fontFamily: fontPlatform,
  },
  playersList: {
    backgroundColor: "transparent",
  },
  playerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  playerRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  playerTextContainer: {
    flex: 1,
  },
  playerName: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    marginBottom: 3,
  },
  playerSubtitle: {
    color: "#64748B",
    fontSize: 12.5,
    fontWeight: "700",
    letterSpacing: 0.6,
    fontFamily: fontPlatform,
  },
  viewStatsButton: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  viewStatsText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  summaryTile: {
    backgroundColor: "#0F172A",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 18,
    marginTop: 8,
  },
  summaryLabel: {
    color: "#5C6B82",
    fontSize: 12.5,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
    marginBottom: 10,
  },
  summaryPill: {
    backgroundColor: "#1E293B",
    borderRadius: 8,
    width: 80,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  summaryPillValue: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  floatingFabButton: {
    position: "absolute",
    bottom: 100,
    right: 20,
    zIndex: 50,
    width: 54,
    height: 54,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 8,
  },
  navContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 40,
    backgroundColor: "#070D19",
    borderTopWidth: 1,
    borderTopColor: "#1E293B",
    paddingBottom: 24,
    paddingTop: 8,
    paddingHorizontal: 0,
  },
  tabsRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: "700",
    marginTop: 4,
    fontFamily: fontPlatform,
  },
  tabLabelActive: {
    color: "#FFFFFF",
  },
  tabLabelInactive: {
    color: "#64748B",
  },
  fabBackdrop: {
    flex: 1,
    backgroundColor: "rgba(5, 10, 24, 0.82)",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  fabMenuCard: {
    backgroundColor: "#0F172A",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    width: 220,
    marginBottom: 16,
    paddingVertical: 4,
  },
  fabActionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  fabActionText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
    fontFamily: fontPlatform,
  },
  fabDivider: {
    height: 1,
    backgroundColor: "#1E293B",
    marginHorizontal: 12,
  },
  closeFabButton: {
    width: 54,
    height: 54,
    borderRadius: 14,
    backgroundColor: "#111C35",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 10, 24, 0.85)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#0F172A",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 20,
    maxHeight: "85%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  teamBannerCard: {
    backgroundColor: "#070D19",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 20,
    marginBottom: 16,
  },
  sportBadge: {
    backgroundColor: "#1E293B",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
    marginBottom: 10,
  },
  sportBadgeText: {
    color: "#00C8FF",
    fontSize: 11,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  teamNameTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    marginBottom: 4,
  },
  divisionText: {
    color: "#94A3B8",
    fontSize: 14,
    fontFamily: fontPlatform,
    marginBottom: 16,
  },
  recordBox: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  recordLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  recordValue: {
    color: "#00C8FF",
    fontSize: 15,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  manageCtaButton: {
    backgroundColor: "#2563EB",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 20,
  },
  manageCtaText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
