import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  fixedHeaderContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 50,
  },
  sectionLabel: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
    textTransform: "uppercase",
    marginBottom: 8,
    marginTop: 22,
  },
  cardBox: {
    backgroundColor: "#0F172A",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E293B",
    overflow: "hidden",
  },
  rowItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  rowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  itemLeftContent: {
    flex: 1,
    marginRight: 12,
  },
  itemTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  itemSubtext: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "500",
    fontFamily: fontPlatform,
    marginTop: 2,
  },
  logoutButton: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 32,
  },
  logoutText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1.5,
    fontFamily: fontBoldPlatform,
  },
  confirmOverlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(5, 10, 24, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  confirmDialogCard: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    alignItems: "center",
  },
  logoutIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  logoutConfirmTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
    marginBottom: 8,
  },
  logoutConfirmMessage: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    fontFamily: fontPlatform,
    marginBottom: 20,
  },
  confirmButtonRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  cancelLogoutButton: {
    flex: 1,
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
  },
  cancelLogoutText: {
    color: "#94A3B8",
    fontSize: 13.5,
    fontWeight: "800",
    fontFamily: fontPlatform,
  },
  confirmLogoutButton: {
    flex: 1,
    backgroundColor: "#EF4444",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
  },
  confirmLogoutText: {
    color: "#FFFFFF",
    fontSize: 13.5,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 10, 24, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContentCard: {
    backgroundColor: "#0F172A",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 24,
    width: "100%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  inputLabel: {
    color: "#94A3B8",
    fontSize: 11.5,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: fontPlatform,
    marginTop: 12,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    paddingHorizontal: 14,
    height: 48,
  },
  passwordInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
    fontFamily: fontPlatform,
  },
  errorText: {
    color: "#EF4444",
    fontSize: 12.5,
    fontWeight: "700",
    fontFamily: fontPlatform,
    marginTop: 12,
    textAlign: "center",
  },
  primaryCtaBtn: {
    backgroundColor: "#00C8FF",
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 22,
  },
  primaryCtaDisabled: {
    opacity: 0.5,
  },
  primaryCtaBtnText: {
    color: "#070D19",
    fontSize: 14.5,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  successIconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "rgba(0, 200, 255, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    alignSelf: "center",
  },
  successTitle: {
    color: "#00C8FF",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
    marginBottom: 8,
  },
  successMessage: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    fontFamily: fontPlatform,
    marginBottom: 24,
  },
});

export default styles;
