import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  fixedHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: "#070D19",
    paddingHorizontal: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1.5,
    fontFamily: fontBoldPlatform,
  },
  closeIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  titleBlock: {
    marginTop: 14,
    marginBottom: 24,
  },
  headline: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
    marginBottom: 6,
  },
  subtitle: {
    color: "#8E9BAE",
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fontPlatform,
  },
  dropzoneCard: {
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.25)",
    borderStyle: "dashed",
    borderRadius: 12,
    backgroundColor: "rgba(14, 22, 38, 0.5)",
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 28,
  },
  dropzoneIconBox: {
    width: 64,
    height: 64,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  dropzoneTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
    marginBottom: 4,
    textAlign: "center",
  },
  dropzoneSubtext: {
    color: "#8E9BAE",
    fontSize: 13,
    fontFamily: fontPlatform,
    marginBottom: 18,
  },
  actionButtonsRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  browseButton: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  browseButtonText: {
    color: "#070D19",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontBoldPlatform,
  },
  cameraButton: {
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  cameraButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  sectionLabel: {
    color: "#8E9BAE",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
    marginBottom: 12,
  },
  filesList: {
    gap: 10,
    marginBottom: 24,
  },
  fileCard: {
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fileCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 12,
  },
  fileBadge: {
    width: 42,
    height: 42,
    borderRadius: 6,
    backgroundColor: "#162032",
    borderWidth: 1,
    borderColor: "#243248",
    justifyContent: "center",
    alignItems: "center",
  },
  fileName: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: fontPlatform,
    marginBottom: 2,
  },
  fileMeta: {
    color: "#8E9BAE",
    fontSize: 12,
    fontFamily: fontPlatform,
  },
  fileActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  iconControlBtn: {
    width: 34,
    height: 34,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#243248",
    backgroundColor: "#162032",
    justifyContent: "center",
    alignItems: "center",
  },
  metaGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  metaBox: {
    flex: 1,
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    padding: 12,
  },
  metaLabel: {
    color: "#64748B",
    fontSize: 10.5,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: fontPlatform,
    marginBottom: 4,
  },
  metaValue: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  uploadCtaButton: {
    backgroundColor: "#FFFFFF",
    height: 52,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 4,
    marginBottom: 14,
  },
  uploadCtaText: {
    color: "#070D19",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(3, 7, 18, 0.82)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  previewModalCard: {
    width: "100%",
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 16,
    padding: 20,
  },
  previewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  previewTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.8,
    fontFamily: fontBoldPlatform,
  },
  previewBody: {
    backgroundColor: "#162032",
    borderWidth: 1,
    borderColor: "#243248",
    borderRadius: 8,
    padding: 16,
    marginBottom: 18,
    alignItems: "center",
  },
  previewMetaText: {
    color: "#8E9BAE",
    fontSize: 13,
    fontFamily: fontPlatform,
    lineHeight: 20,
    textAlign: "center",
  },
  modalCtaButton: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    height: 46,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  modalCtaText: {
    color: "#070D19",
    fontSize: 13.5,
    fontWeight: "900",
    letterSpacing: 0.8,
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
