import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  fixedHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: "#070D19",
    paddingHorizontal: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 14,
    width: "100%",
  },
  headerTitleBeside: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: fontBoldPlatform,
  },
  backIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  topTitleSection: {
    marginTop: 14,
    marginBottom: 20,
  },
  screenTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
    marginBottom: 10,
  },
  accentUnderline: {
    height: 2,
    backgroundColor: "#FFFFFF",
    width: "100%",
    borderRadius: 1,
  },
  cardSection: {
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
  },
  subLabelHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  subLabel: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
  },
  swipeHintText: {
    color: "#64748B",
    fontSize: 11,
    fontStyle: "italic",
    fontFamily: fontPlatform,
  },
  cardDivider: {
    height: 1,
    backgroundColor: "#1E293B",
    marginVertical: 10,
  },
  twoColumnGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  identityCol: {
    flex: 1,
  },
  identityLabel: {
    color: "#64748B",
    fontSize: 10.5,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontPlatform,
    marginBottom: 4,
  },
  identityValue: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
    lineHeight: 20,
  },
  tableCard: {
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  tableHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  tableHeaderColName: {
    width: 150,
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontPlatform,
  },
  tableHeaderColStat: {
    width: 65,
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    textAlign: "right",
    fontFamily: fontPlatform,
  },
  tableDataRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#162032",
  },
  totalsRow: {
    borderBottomWidth: 0,
    paddingTop: 14,
    paddingBottom: 8,
  },
  cellNameText: {
    width: 150,
    color: "#FFFFFF",
    fontSize: 13.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  cellStatText: {
    width: 65,
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "right",
    fontFamily: fontPlatform,
  },
  cellStatInput: {
    width: 58,
    backgroundColor: "#162032",
    borderWidth: 1,
    borderColor: "#00C8FF",
    borderRadius: 4,
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
    paddingVertical: 4,
    paddingHorizontal: 6,
    marginLeft: 7,
  },
  shootingGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  efficiencyCard: {
    flex: 1,
    backgroundColor: "#162032",
    borderWidth: 1,
    borderColor: "#243248",
    borderRadius: 6,
    padding: 12,
    alignItems: "center",
  },
  effLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontPlatform,
    marginBottom: 6,
  },
  effValue: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  possessionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 10,
  },
  metricCard: {
    width: "48%",
    backgroundColor: "#162032",
    borderWidth: 1,
    borderColor: "#243248",
    borderLeftWidth: 4,
    borderLeftColor: "#3B82F6",
    borderRadius: 6,
    padding: 12,
  },
  metricCardRed: {
    borderLeftColor: "#EF4444",
  },
  metricLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontPlatform,
    marginBottom: 4,
  },
  metricValue: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  footnoteText: {
    color: "#64748B",
    fontSize: 11,
    fontStyle: "italic",
    fontFamily: fontPlatform,
    marginTop: 6,
  },
  actionStack: {
    gap: 12,
    marginTop: 10,
    marginBottom: 14,
  },
  confirmButton: {
    backgroundColor: "#FFFFFF",
    height: 52,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  confirmButtonText: {
    color: "#070D19",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  editButton: {
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "#1E293B",
    height: 52,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  editButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(3, 7, 18, 0.82)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  successModalCard: {
    width: "100%",
    backgroundColor: "#0E1626",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.35)",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#00C8FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  successIconBadge: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(0, 200, 255, 0.12)",
    borderWidth: 1.5,
    borderColor: "rgba(0, 200, 255, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  successModalTitle: {
    color: "#FFFFFF",
    fontSize: 17.5,
    fontWeight: "900",
    letterSpacing: 0.8,
    textAlign: "center",
    fontFamily: fontBoldPlatform,
    marginBottom: 8,
  },
  successModalSubtitle: {
    color: "#8E9BAE",
    fontSize: 13.5,
    lineHeight: 20,
    textAlign: "center",
    fontFamily: fontPlatform,
    marginBottom: 20,
  },
  successSummaryBox: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
    marginBottom: 24,
  },
  summaryChip: {
    flex: 1,
    backgroundColor: "#162032",
    borderWidth: 1,
    borderColor: "#243248",
    borderRadius: 8,
    padding: 10,
    alignItems: "center",
  },
  chipLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontPlatform,
    marginBottom: 4,
  },
  chipValue: {
    color: "#00C8FF",
    fontSize: 13,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  modalCtaButton: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    height: 48,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  modalCtaText: {
    color: "#070D19",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
