import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  topHeader: {
    height: '58px',
    backgroundColor: '#FFFFFF',
    borderBottom: '1px solid #E2E8F0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 28px',
    flexShrink: 0,
    zIndex: 40,
    boxSizing: 'border-box',
  },
  brandLogo: {
    fontSize: '20px',
    fontWeight: 900,
    letterSpacing: '0.18em',
    color: '#0B132B',
    textDecoration: 'none',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  bellBtn: {
    position: 'relative',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px',
  },
  bellDot: {
    position: 'absolute',
    top: '4px',
    right: '4px',
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#EF4444',
  },
  vDivider: {
    width: '1px',
    height: '26px',
    backgroundColor: '#E2E8F0',
  },
  profileBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  profileInfo: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  profileRole: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#94A3B8',
    letterSpacing: '0.12em',
  },
  profileName: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.04em',
    marginTop: '3px',
  },
  avatarCircle: {
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    border: '2px solid #0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#0B132B',
  },
  layoutBody: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 58px)',
    overflow: 'hidden',
  },
  sidebar: {
    width: '220px',
    backgroundColor: '#FFFFFF',
    borderRight: '1px solid #E2E8F0',
    padding: '20px 14px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    flexShrink: 0,
    height: '100%',
    boxSizing: 'border-box',
    overflowY: 'auto',
  },
  sidebarTop: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  createMatchBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '10px 14px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.1em',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    width: '100%',
    boxSizing: 'border-box',
  },
  navGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '9px 12px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textDecoration: 'none',
    color: '#64748B',
  },
  navItemActive: {
    backgroundColor: '#F0F9FF',
    color: '#0284C7',
    borderLeft: '4px solid #0284C7',
  },
  logoutBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    color: '#64748B',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  },
  contentArea: {
    flex: 1,
    padding: '24px 32px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    overflowX: 'hidden',
    height: '100%',
    boxSizing: 'border-box',
  },
  pageHeader: {
    marginBottom: '20px',
  },
  pageTitle: {
    fontSize: '28px',
    fontWeight: 900,
    letterSpacing: '0.02em',
    color: '#0B132B',
    margin: '0 0 4px 0',
  },
  pageSubtitle: {
    fontSize: '12px',
    color: '#64748B',
    margin: 0,
    fontStyle: 'italic',
  },
  sectionWrap: {
    marginBottom: '20px',
  },
  sectionBanner: {
    display: 'inline-block',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '4px 10px',
    fontSize: '10px',
    fontWeight: 900,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    marginBottom: '8px',
  },
  sectionBox: {
    border: '1px solid #0B132B',
    backgroundColor: '#FFFFFF',
    width: '100%',
  },
  itemRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid #0B132B',
    cursor: 'pointer',
    textDecoration: 'none',
    color: '#0B132B',
    transition: 'background-color 0.1s ease',
  },
  itemRowNoBorder: {
    borderBottom: 'none',
  },
  itemLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  itemTextWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  itemTitle: {
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
    margin: 0,
  },
  itemDesc: {
    fontSize: '11px',
    color: '#64748B',
    margin: 0,
  },
  switchTrack: {
    width: '42px',
    height: '24px',
    backgroundColor: '#94A3B8',
    border: 'none',
    borderRadius: '2px',
    position: 'relative',
    cursor: 'pointer',
    padding: 0,
    outline: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    flexShrink: 0,
    transition: 'background-color 0.15s ease',
  },
  switchTrackActive: {
    backgroundColor: '#0B132B',
  },
  switchThumb: {
    width: '16px',
    height: '16px',
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    top: '4px',
    left: '4px',
    transition: 'transform 0.15s cubic-bezier(0.4, 0, 0.2, 1)',
    pointerEvents: 'none',
    borderRadius: '1px',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.15)',
  },
  switchThumbActive: {
    transform: 'translateX(18px)',
  },
};
