import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  layoutBody: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 58px)',
    overflow: 'hidden',
  },
  contentArea: {
    flex: 1,
    padding: '20px 32px 24px 32px',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    gap: '28px',
    alignItems: 'stretch',
  },
  calendarSection: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    boxSizing: 'border-box',
  },
  headerControlsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '14px',
    width: '100%',
    height: '32px',
    flexShrink: 0,
  },
  titleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  monthTitle: {
    fontSize: '26px',
    fontWeight: 900,
    letterSpacing: '0.02em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  stepBtnGroup: {
    display: 'flex',
    border: '2px solid #0B132B',
  },
  stepBtn: {
    width: '30px',
    height: '30px',
    background: 'none',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#0B132B',
  },
  stepDivider: {
    width: '1px',
    height: '30px',
    backgroundColor: '#0B132B',
  },
  calendarTable: {
    width: '100%',
    borderCollapse: 'collapse',
    border: '2px solid #0B132B',
    tableLayout: 'fixed',
    flex: 1,
    height: 'calc(100% - 46px)',
  },
  calTh: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    padding: '8px 10px',
    textAlign: 'center',
    textTransform: 'uppercase',
    borderRight: '1px solid #1E293B',
    lineHeight: 1,
    height: '30px',
  },
  calTd: {
    border: '1px solid #CBD5E1',
    height: 'calc((100% - 30px) / 5)',
    minHeight: '86px',
    verticalAlign: 'top',
    padding: '6px 8px',
    cursor: 'pointer',
    position: 'relative',
    transition: 'background-color 0.1s ease',
    boxSizing: 'border-box',
  },
  calTdEmpty: {
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
  },
  dateNum: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#64748B',
    lineHeight: '1',
    marginBottom: '4px',
  },
  dateNumActive: {
    color: '#0284C7',
  },
  badgeWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  matchBadge: {
    padding: '2px 5px',
    borderRadius: '3px',
    fontSize: '9px',
    fontWeight: 800,
    letterSpacing: '0.02em',
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
    textDecoration: 'none',
    border: '1px solid transparent',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    cursor: 'pointer',
    lineHeight: 1.2,
  },
  bbBadge: {
    backgroundColor: '#E0F2FE',
    color: '#0369A1',
    border: '1px solid #BAE6FD',
  },
  vbBadge: {
    backgroundColor: '#F3E8FF',
    color: '#7E22CE',
    border: '1px solid #E9D5FF',
  },
  fbBadge: {
    backgroundColor: '#FEF3C7',
    color: '#B45309',
    border: '1px solid #FDE68A',
  },

  /* Right Side Details Column */
  detailsSection: {
    width: '340px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    paddingTop: '46px',
    boxSizing: 'border-box',
    height: '100%',
  },
  detailsCard: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    boxSizing: 'border-box',
  },
  detailsBanner: {
    backgroundColor: '#0B132B',
    padding: '12px 18px',
    color: '#FFFFFF',
    flexShrink: 0,
  },
  detailsTitle: {
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#FFFFFF',
    margin: 0,
    textTransform: 'uppercase',
  },
  detailsDateSub: {
    fontSize: '10px',
    fontWeight: 700,
    letterSpacing: '0.1em',
    color: '#94A3B8',
    margin: '3px 0 0 0',
    textTransform: 'uppercase',
  },
  detailsBody: {
    padding: '16px 16px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    flex: 1,
    gap: '14px',
    boxSizing: 'border-box',
  },
  matchCardWrapper: {
    position: 'relative',
    paddingTop: '12px',
  },
  timeTag: {
    position: 'absolute',
    top: 0,
    left: '14px',
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    padding: '3px 10px',
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0369A1',
    zIndex: 2,
  },
  matchCardOuter: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '16px 16px 12px 16px',
    boxShadow: '5px 5px 0px #0B132B',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  sportPill: {
    display: 'inline-block',
    alignSelf: 'flex-start',
    backgroundColor: '#BAE6FD',
    border: '1px solid #0B132B',
    padding: '2px 8px',
    fontSize: '10px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  teamList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  teamRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  teamLetterBox: {
    width: '26px',
    height: '26px',
    border: '2px solid #0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: 900,
    color: '#0B132B',
  },
  teamName: {
    fontSize: '13px',
    fontWeight: 900,
    color: '#0B132B',
    letterSpacing: '0.03em',
    textTransform: 'uppercase',
  },
  dashedDivider: {
    borderTop: '1px dashed #CBD5E1',
    margin: '2px 0',
  },
  officialsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  officialsLabel: {
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  officialsAvatars: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    color: '#0B132B',
  },
  logisticsBox: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '14px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  logisticsTitle: {
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  logisticsGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  logisticsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '11px',
  },
  logisticsKey: {
    color: '#64748B',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  logisticsVal: {
    color: '#0B132B',
    fontWeight: 900,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
};
