import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.4)',
    zIndex: 80,
    transition: 'opacity 0.25s ease-in-out',
  },
  drawer: {
    position: 'fixed',
    top: '58px',
    right: 0,
    height: 'calc(100vh - 58px)',
    width: '380px',
    maxWidth: '90vw',
    backgroundColor: '#FFFFFF',
    borderLeft: '2px solid #0B132B',
    boxShadow: '-8px 0 24px rgba(0, 0, 0, 0.12)',
    zIndex: 90,
    display: 'flex',
    flexDirection: 'column',
    transform: 'translateX(0)',
    transition: 'transform 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  drawerHeader: {
    backgroundColor: '#0B132B',
    padding: '24px 28px',
    color: '#FFFFFF',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontSize: '20px',
    fontWeight: '900',
    letterSpacing: '0.08em',
    color: '#FFFFFF',
    margin: 0,
    textTransform: 'uppercase',
  },
  headerSubtitle: {
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.12em',
    color: '#94A3B8',
    margin: '4px 0 0 0',
    textTransform: 'uppercase',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#FFFFFF',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerBody: {
    padding: '28px 24px',
    overflowY: 'auto',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  matchCardWrapper: {
    position: 'relative',
    paddingTop: '14px',
  },
  timeTag: {
    position: 'absolute',
    top: '0',
    left: '16px',
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    padding: '4px 12px',
    fontSize: '12px',
    fontWeight: '900',
    letterSpacing: '0.08em',
    color: '#0369A1',
    zIndex: 2,
  },
  matchCardOuter: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '24px 20px 18px 20px',
    boxShadow: '6px 6px 0px #0B132B',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  sportPill: {
    display: 'inline-block',
    alignSelf: 'flex-start',
    backgroundColor: '#BAE6FD',
    border: '1px solid #0B132B',
    padding: '3px 10px',
    fontSize: '11px',
    fontWeight: '900',
    letterSpacing: '0.1em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  teamList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  teamRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  teamLetterBox: {
    width: '32px',
    height: '32px',
    border: '2px solid #0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '16px',
    fontWeight: '900',
    color: '#0B132B',
  },
  teamName: {
    fontSize: '16px',
    fontWeight: '900',
    color: '#0B132B',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  dashedDivider: {
    borderTop: '2px dashed #CBD5E1',
    margin: '4px 0',
  },
  officialsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  officialsLabel: {
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.1em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  officialsAvatars: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#0B132B',
  },
  logisticsBox: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  logisticsTitle: {
    fontSize: '13px',
    fontWeight: '900',
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
    margin: 0,
  },
  logisticsGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  logisticsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '12px',
  },
  logisticsKey: {
    color: '#64748B',
    fontWeight: '700',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  logisticsVal: {
    color: '#0B132B',
    fontWeight: '900',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
};
