import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#F8FAFC',
  },
  header: {
    width: '100%',
    backgroundColor: '#060B18',
    borderBottom: '1px solid #1E293B',
    padding: '16px 48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 50,
  },
  logo: {
    fontSize: '22px',
    fontWeight: '900',
    letterSpacing: '0.25em',
    color: '#FFFFFF',
    textDecoration: 'none',
  },
  logoSup: {
    fontSize: '10px',
    fontWeight: '800',
    verticalAlign: 'super',
    marginLeft: '3px',
    letterSpacing: '0.05em',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  loginLink: {
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '0.15em',
    color: '#94A3B8',
    textDecoration: 'none',
  },
  regBtn: {
    padding: '8px 18px',
    borderRadius: '4px',
    backgroundColor: '#E2E8F0',
    color: '#0B132B',
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '0.15em',
    textDecoration: 'none',
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 16px',
  },
  title: {
    fontSize: '28px',
    fontWeight: '800',
    letterSpacing: '0.05em',
    color: '#0B132B',
    marginBottom: '28px',
    textAlign: 'center',
  },
  card: {
    width: '92%',
    maxWidth: '720px',
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E2E8F0',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.05)',
    padding: '36px',
    boxSizing: 'border-box',
  },
  stepRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '20px',
    paddingBottom: '8px',
  },
  stepBadge: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: '700',
    padding: '4px 10px',
    borderRadius: '4px',
    letterSpacing: '0.1em',
  },
  stepTitle: {
    fontSize: '16px',
    fontWeight: '800',
    letterSpacing: '0.08em',
    color: '#0B132B',
    margin: 0,
  },
  error: {
    marginBottom: '20px',
    padding: '12px 16px',
    backgroundColor: '#FEF2F2',
    border: '1px solid #FECACA',
    borderRadius: '6px',
    color: '#B91C1C',
    fontSize: '12px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '18px',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
  },
  fieldFull: {
    gridColumn: '1 / -1',
    display: 'flex',
    flexDirection: 'column',
  },
  label: {
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.1em',
    color: '#334155',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    height: '46px',
    padding: '0 14px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '6px',
    fontSize: '14px',
    color: '#0B132B',
    outline: 'none',
    boxSizing: 'border-box',
  },
  inputWrap: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  passInput: {
    width: '100%',
    height: '46px',
    paddingLeft: '14px',
    paddingRight: '42px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '6px',
    fontSize: '14px',
    color: '#0B132B',
    outline: 'none',
    boxSizing: 'border-box',
  },
  eyeBtn: {
    position: 'absolute',
    right: '14px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    color: '#94A3B8',
  },
  selectWrap: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  select: {
    width: '100%',
    height: '46px',
    padding: '0 40px 0 14px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '6px',
    fontSize: '14px',
    color: '#0B132B',
    outline: 'none',
    appearance: 'none',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  selectIcon: {
    position: 'absolute',
    right: '14px',
    width: '16px',
    height: '16px',
    color: '#94A3B8',
    pointerEvents: 'none',
  },
  certRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    paddingTop: '6px',
  },
  certCheck: {
    width: '16px',
    height: '16px',
    marginTop: '2px',
    cursor: 'pointer',
    accentColor: '#0B132B',
    flexShrink: 0,
  },
  certLabel: {
    fontSize: '11px',
    lineHeight: '1.5',
    color: '#64748B',
    cursor: 'pointer',
    userSelect: 'none',
  },
  submitBtn: {
    width: '100%',
    height: '48px',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '0.15em',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    marginTop: '8px',
  },
  footer: {
    width: '100%',
    backgroundColor: '#F3F4F6',
    borderTop: '1px solid #E5E7EB',
    padding: '20px 48px',
  },
  footWrap: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '16px',
  },
  footLogo: {
    fontSize: '16px',
    fontWeight: '800',
    letterSpacing: '0.2em',
    color: '#94A3B8',
  },
  copy: {
    fontSize: '11px',
    fontWeight: '500',
    letterSpacing: '0.08em',
    color: '#64748B',
  },
  footLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
  },
  footLink: {
    fontSize: '11px',
    fontWeight: '600',
    letterSpacing: '0.1em',
    color: '#64748B',
    cursor: 'pointer',
  },
};
