import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  sidebar: {
    width: '240px',
    backgroundColor: '#FFFFFF',
    borderRight: '1.5px solid #0F172A',
    padding: '24px 16px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    flexShrink: 0,
    boxSizing: 'border-box',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  },
  topSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  navLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 14px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.08em',
    textDecoration: 'none',
    color: '#64748B',
    backgroundColor: 'transparent',
    borderLeft: '4px solid transparent',
    transition: 'all 0.15s ease',
  },
  navLinkActive: {
    color: '#0F172A',
    backgroundColor: '#F1F5F9',
    borderLeft: '4px solid #0F172A',
  },
  navLinkHovered: {
    color: '#0F172A',
    backgroundColor: '#F8FAFC',
    borderLeft: '4px solid #CBD5E1',
  },
  logoutBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 14px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.08em',
    color: '#EF4444',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    transition: 'all 0.15s ease',
  },
  logoutBtnHovered: {
    color: '#DC2626',
    backgroundColor: '#FEF2F2',
  },

  /* Logout Confirmation Modal */
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  },
  logoutCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0F172A',
    width: '90%',
    maxWidth: '400px',
    padding: '24px 28px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.2)',
    boxSizing: 'border-box',
  },
  modalHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  logoutTitle: {
    fontSize: '14px',
    fontWeight: '900',
    color: '#0F172A',
    margin: 0,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#64748B',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutDesc: {
    fontSize: '12px',
    color: '#64748B',
    margin: '0 0 20px 0',
    lineHeight: 1.6,
    fontWeight: '500',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  logoutCancelBtn: {
    padding: '9px 16px',
    border: '1.5px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#64748B',
    fontWeight: '800',
    fontSize: '11px',
    cursor: 'pointer',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  logoutConfirmBtn: {
    padding: '9px 18px',
    border: 'none',
    backgroundColor: '#DC2626',
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: '11px',
    cursor: 'pointer',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    transition: 'background-color 0.15s ease',
  },
};
