import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  topHeader: {
    height: '58px',
    backgroundColor: '#FFFFFF',
    borderBottom: '1px solid #E2E8F0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 28px',
    flexShrink: 0,
    zIndex: 40,
    boxSizing: 'border-box',
  },
  brandLogo: {
    fontSize: '20px',
    fontWeight: 900,
    letterSpacing: '0.18em',
    color: '#0B132B',
    textDecoration: 'none',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  bellBtn: {
    position: 'relative',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px',
  },
  bellDot: {
    position: 'absolute',
    top: '4px',
    right: '4px',
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#EF4444',
  },
  vDivider: {
    width: '1px',
    height: '26px',
    backgroundColor: '#E2E8F0',
  },
  profileBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  profileInfo: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  profileRole: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#94A3B8',
    letterSpacing: '0.12em',
    lineHeight: '1',
  },
  profileName: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.04em',
    marginTop: '3px',
  },
  avatarCircle: {
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    border: '2px solid #0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#0B132B',
  },
  layoutBody: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 58px)',
    overflow: 'hidden',
  },
  sidebar: {
    width: '220px',
    backgroundColor: '#FFFFFF',
    borderRight: '1px solid #E2E8F0',
    padding: '20px 14px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    flexShrink: 0,
    height: '100%',
    boxSizing: 'border-box',
    overflowY: 'auto',
  },
  sidebarTop: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  createMatchBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '10px 14px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.1em',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    width: '100%',
    boxSizing: 'border-box',
  },
  navGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '9px 12px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textDecoration: 'none',
    color: '#64748B',
    transition: 'all 0.15s ease',
  },
  navItemActive: {
    backgroundColor: '#F0F9FF',
    color: '#0284C7',
    borderLeft: '4px solid #0284C7',
  },
  logoutBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    color: '#64748B',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
  },
  contentArea: {
    flex: 1,
    padding: '24px 32px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    overflowX: 'hidden',
    height: '100%',
    boxSizing: 'border-box',
  },
  pageHeader: {
    marginBottom: '20px',
  },
  pageTitle: {
    fontSize: '28px',
    fontWeight: 900,
    letterSpacing: '0.02em',
    color: '#0B132B',
    margin: '0 0 4px 0',
  },
  pageSubtitle: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#64748B',
    margin: 0,
    textTransform: 'uppercase',
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '16px',
    marginBottom: '24px',
    width: '100%',
  },
  kpiBox: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    padding: '16px 20px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    boxSizing: 'border-box',
  },
  kpiLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    marginBottom: '4px',
  },
  kpiValue: {
    fontSize: '38px',
    fontWeight: 900,
    letterSpacing: '0.01em',
    color: '#0B132B',
    lineHeight: '1',
    margin: 0,
  },
  sectionHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  sectionHeading: {
    fontSize: '13px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
    margin: 0,
  },
  viewAllLink: {
    fontSize: '11px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.05em',
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
  },
  tableFrame: {
    border: '1px solid #0B132B',
    marginBottom: '24px',
    width: '100%',
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    padding: '10px 14px',
    textTransform: 'uppercase',
    borderRight: '1px solid #1E293B',
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '12px 14px',
    fontSize: '13px',
    color: '#0B132B',
    borderBottom: '1px solid #E2E8F0',
    borderRight: '1px solid #E2E8F0',
  },
  tdMatchId: {
    fontWeight: 800,
    letterSpacing: '0.04em',
    whiteSpace: 'nowrap',
  },
  statusBadge: {
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: '4px',
    border: '1px solid #FDE047',
    backgroundColor: '#FEF9C3',
    color: '#854D0E',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  recentActivityCard: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    width: '100%',
    marginBottom: '24px',
  },
  activityHead: {
    backgroundColor: '#F1F5F9',
    borderBottom: '1px solid #0B132B',
    padding: '10px 16px',
    fontSize: '12px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  activityBody: {
    padding: '16px 18px',
    minHeight: '110px',
  },
  emptyNotice: {
    color: '#94A3B8',
    fontSize: '12px',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '18px 0',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    width: '92%',
    maxWidth: '480px',
    padding: '24px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.04em',
    margin: '0 0 16px 0',
  },
  formRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    marginBottom: '12px',
  },
  formLabel: {
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  formInput: {
    border: '1px solid #CBD5E1',
    borderRadius: '4px',
    padding: '8px 10px',
    fontSize: '12px',
    color: '#0B132B',
    outline: 'none',
  },
  modalBtns: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    marginTop: '18px',
  },
  cancelBtn: {
    padding: '8px 14px',
    border: '1px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#64748B',
    fontWeight: 700,
    fontSize: '11px',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  saveBtn: {
    padding: '8px 16px',
    border: 'none',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontWeight: 800,
    fontSize: '11px',
    borderRadius: '4px',
    cursor: 'pointer',
  },
};
