import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#F8FAFC',
  },
  header: {
    width: '100%',
    backgroundColor: '#060B18',
    borderBottom: '1px solid #1E293B',
    padding: '16px 48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 50,
  },
  logo: {
    fontSize: '22px',
    fontWeight: '900',
    letterSpacing: '0.25em',
    color: '#FFFFFF',
    textDecoration: 'none',
  },
  logoSup: {
    fontSize: '10px',
    fontWeight: '800',
    verticalAlign: 'super',
    marginLeft: '3px',
    letterSpacing: '0.05em',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  userBadge: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#94A3B8',
    letterSpacing: '0.05em',
  },
  logoutBtn: {
    padding: '8px 18px',
    borderRadius: '4px',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '0.12em',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    cursor: 'pointer',
  },
  main: {
    flex: 1,
    padding: '40px 24px',
    maxWidth: '1100px',
    width: '100%',
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  welcomeBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E2E8F0',
    borderTop: '4px solid #0B132B',
    padding: '32px',
    marginBottom: '24px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
  },
  welcomeTitle: {
    fontSize: '22px',
    fontWeight: '800',
    color: '#0B132B',
    margin: '0 0 8px 0',
    letterSpacing: '0.03em',
  },
  welcomeSub: {
    fontSize: '13px',
    color: '#64748B',
    margin: 0,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '20px',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E2E8F0',
    padding: '24px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.02)',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  cardHead: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    color: '#0B132B',
    fontWeight: '700',
    fontSize: '13px',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  cardValue: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#0B132B',
    margin: 0,
  },
  cardLabel: {
    fontSize: '11px',
    color: '#64748B',
    margin: 0,
  },
  tag: {
    display: 'inline-block',
    padding: '4px 10px',
    backgroundColor: '#F1F5F9',
    color: '#0B132B',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.05em',
    alignSelf: 'flex-start',
  },
  footer: {
    width: '100%',
    backgroundColor: '#F3F4F6',
    borderTop: '1px solid #E5E7EB',
    padding: '20px 48px',
  },
  footWrap: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '16px',
  },
  footLogo: {
    fontSize: '16px',
    fontWeight: '800',
    letterSpacing: '0.2em',
    color: '#94A3B8',
  },
  copy: {
    fontSize: '11px',
    fontWeight: '500',
    letterSpacing: '0.08em',
    color: '#64748B',
  },
};
