import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  fixedHeaderContainer: {
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 120,
  },
  teamHeaderBlock: {
    marginBottom: 28,
  },
  teamNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  teamNameTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -0.5,
    fontFamily: fontBoldPlatform,
    flex: 1,
  },
  editIconButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  clubSubTitleText: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.5,
    fontFamily: fontPlatform,
    textTransform: "uppercase",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  totalBadge: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  totalBadgeText: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  coachCard: {
    backgroundColor: "#0F172A",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 16,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 28,
  },
  cardRoleLabelLeft: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    fontFamily: fontPlatform,
    width: 76,
  },
  coachMainInfo: {
    flex: 1,
  },
  coachNameText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
    marginBottom: 2,
  },
  coachTitleSub: {
    color: "#94A3B8",
    fontSize: 13,
    fontFamily: fontPlatform,
    marginBottom: 8,
  },
  coachTagPill: {
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#00C8FF",
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: "flex-start",
  },
  coachTagText: {
    color: "#00C8FF",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  rosterCard: {
    backgroundColor: "#0F172A",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 16,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  playerRoleLabelLeft: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    fontFamily: fontPlatform,
    width: 76,
  },
  playerMainInfo: {
    flex: 1,
  },
  playerNameText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    marginBottom: 2,
  },
  playerPosMetaText: {
    color: "#00C8FF",
    fontSize: 12.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  fixedBottomContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: "#070D19",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
  },
  primaryCtaButton: {
    backgroundColor: "#0B132B",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryCtaText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1.5,
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
