import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  fixedHeaderContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: "#070D19",
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  deleteTeamHeaderIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  metadataBox: {
    backgroundColor: "#0F172A",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 18,
    marginBottom: 24,
  },
  metadataLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  metadataLabel: {
    color: "#64748B",
    fontSize: 12.5,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
  },
  teamNameText: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
    marginBottom: 16,
  },
  metadataSubRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#1E293B",
    paddingTop: 12,
  },
  subLabel: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    fontFamily: fontPlatform,
    marginBottom: 4,
  },
  sportBadgeOutline: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  sportBadgeOutlineText: {
    color: "#FFFFFF",
    fontSize: 12.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  divisionValue: {
    color: "#00C8FF",
    fontSize: 14.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  rosterHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  rosterTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  rosterCountText: {
    color: "#64748B",
    fontSize: 14.5,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  rosterContainer: {
    backgroundColor: "#0F172A",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    overflow: "hidden",
  },
  rosterRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  rosterRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  avatarCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  playerName: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  miniLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    fontFamily: fontPlatform,
    marginBottom: 3,
    textAlign: "center",
  },
  uniformControlBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    height: 34,
    paddingHorizontal: 6,
    gap: 3,
    minWidth: 48,
  },
  uniformInputBox: {
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    color: "#FFFFFF",
    fontSize: 13.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    textAlign: "center",
    height: 34,
    width: 48,
    paddingHorizontal: 4,
    paddingVertical: 0,
  },
  distanceInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    height: 34,
    width: 58,
    paddingHorizontal: 6,
  },
  distanceNumericInput: {
    color: "#FFFFFF",
    fontSize: 13.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    textAlign: "right",
    paddingVertical: 0,
    paddingHorizontal: 0,
    flex: 1,
  },
  meterUnitText: {
    color: "#00C8FF",
    fontSize: 12,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    marginLeft: 2,
  },
  posText: {
    color: "#00C8FF",
    fontSize: 13,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  addPlayersCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2563EB",
    borderRadius: 12,
    paddingVertical: 16,
    marginTop: 8,
  },
  addPlayersCtaText: {
    color: "#FFFFFF",
    fontSize: 15.5,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 10, 24, 0.85)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#0F172A",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 20,
    maxHeight: "85%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  inputLabel: {
    color: "#64748B",
    fontSize: 12.5,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: fontPlatform,
    marginTop: 14,
    marginBottom: 6,
  },
  modalInput: {
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    color: "#FFFFFF",
    fontSize: 16.5,
    fontWeight: "600",
    fontFamily: fontPlatform,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  sportDropdownContainer: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginVertical: 4,
  },
  sportDropdownPill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
  },
  sportDropdownPillInactive: {
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  sportDropdownPillActive: {
    backgroundColor: "#00C8FF",
  },
  sportDropdownPillText: {
    fontSize: 13.5,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  sportDropdownPillTextInactive: {
    color: "#94A3B8",
  },
  sportDropdownPillTextActive: {
    color: "#070D19",
  },
  primarySaveButton: {
    backgroundColor: "#2563EB",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 24,
    marginBottom: 12,
  },
  disabledSaveButton: {
    backgroundColor: "#1E293B",
    opacity: 0.6,
  },
  primarySaveButtonText: {
    color: "#FFFFFF",
    fontSize: 14.5,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  confirmOverlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(5, 10, 24, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  confirmDialogCard: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    alignItems: "center",
  },
  pickerOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  pickerOptionCode: {
    color: "#00C8FF",
    fontSize: 14,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
    width: 44,
  },
  pickerOptionLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: fontPlatform,
  },
  warningIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  confirmTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
    marginBottom: 8,
  },
  confirmMessage: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    fontFamily: fontPlatform,
    marginBottom: 20,
  },
  confirmButtonRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  cancelConfirmButton: {
    flex: 1,
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  cancelConfirmText: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "800",
    fontFamily: fontPlatform,
  },
  removeConfirmButton: {
    flex: 1,
    backgroundColor: "#EF4444",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  removeConfirmText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  poolRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
  poolRowSelected: {
    borderColor: "#00C8FF",
    backgroundColor: "#111C35",
  },
  poolName: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
  },
  poolSub: {
    color: "#64748B",
    fontSize: 12.5,
    fontFamily: fontPlatform,
  },
  confirmAddBtn: {
    backgroundColor: "#2563EB",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 14,
  },
  disabledAddBtn: {
    backgroundColor: "#1E293B",
    opacity: 0.6,
  },
  confirmAddText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
