import { Platform, StyleSheet } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  fixedHeaderContainer: {
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: "#070D19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 120,
  },
  squadManagementLabel: {
    color: "#00C8FF",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontFamily: fontPlatform,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  titleBadgeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    fontFamily: fontBoldPlatform,
  },
  totalCountBadge: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  totalCountText: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontFamily: fontBoldPlatform,
  },
  accordionCard: {
    backgroundColor: "#0F172A",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    marginBottom: 14,
    overflow: "hidden",
  },
  accordionCardExpanded: {
    borderColor: "#00C8FF",
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  playerInfoLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  playerName: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
    fontFamily: fontBoldPlatform,
    marginBottom: 2,
  },
  playerSubMeta: {
    color: "#94A3B8",
    fontSize: 12.5,
    fontFamily: fontPlatform,
  },
  statusTagPill: {
    backgroundColor: "#0B192C",
    borderWidth: 1,
    borderColor: "#00C8FF",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: "flex-start",
    marginTop: 4,
  },
  statusTagText: {
    color: "#00C8FF",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  expandedFormContent: {
    borderTopWidth: 1,
    borderTopColor: "#1E293B",
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#0B132B",
  },
  formRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  fieldCol: {
    flex: 1,
  },
  inputLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: fontPlatform,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  textInput: {
    backgroundColor: "#FFFFFF",
    borderRadius: 6,
    color: "#0F172A",
    fontSize: 15,
    fontWeight: "600",
    fontFamily: fontPlatform,
    paddingHorizontal: 12,
    paddingVertical: 10,
    height: 46,
  },
  removePlayerButton: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 6,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  removePlayerText: {
    color: "#FFFFFF",
    fontSize: 12.5,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  addMoreButton: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    marginBottom: 20,
  },
  addMoreText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  fixedBottomContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: "#070D19",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
  },
  primaryCtaButton: {
    backgroundColor: "#0B132B",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 8,
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  primaryCtaDisabled: {
    opacity: 0.5,
  },
  primaryCtaText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1.5,
    fontFamily: fontBoldPlatform,
  },
});

export default styles;
