import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  dashboardContainer: {
    flex: 1,
    backgroundColor: "#080F21",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
  },
  categoryBadge: {
    backgroundColor: "#38BDF8",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
    alignSelf: "flex-start",
    shadowColor: "#38BDF8",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 3,
  },
  categoryBadgeText: {
    color: "#080F21",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  sectionHeadingContainer: {
    marginTop: 18,
    marginBottom: 20,
  },
  mainTitle: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  activeUnderline: {
    width: 60,
    height: 3,
    backgroundColor: "#38BDF8",
    borderRadius: 2,
    marginTop: 6,
  },
  metricsGridRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 14,
  },
  metricCard: {
    flex: 1,
    backgroundColor: "#111C35",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#1E2C4A",
  },
  metricLabel: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  metricValueLarge: {
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "900",
    marginTop: 6,
  },
  secondaryMetricCard: {
    backgroundColor: "#111C35",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#1E2C4A",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  secondaryMetricLeft: {
    justifyContent: "center",
  },
  reboundsRow: {
    flexDirection: "row",
    alignItems: "baseline",
    marginTop: 4,
  },
  reboundsValue: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
  },
  reboundsSubtext: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
    marginLeft: 6,
    opacity: 0.9,
  },
  reboundsLevelIndicator: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
  },
  levelBar: {
    width: 6,
    height: 24,
    borderRadius: 3,
  },
  levelBarActive: {
    backgroundColor: "#38BDF8",
    shadowColor: "#38BDF8",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
  },
  levelBarInactive: {
    backgroundColor: "#1C2A44",
  },
  sectionBlock: {
    marginBottom: 24,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  cyanAccentBar: {
    width: 3,
    height: 16,
    backgroundColor: "#38BDF8",
    borderRadius: 2,
    marginRight: 8,
  },
  sectionTitleText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  progressItem: {
    marginBottom: 14,
  },
  progressHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  progressLabelText: {
    color: "#CBD5E1",
    fontSize: 14,
    fontWeight: "600",
  },
  progressValueText: {
    color: "#38BDF8",
    fontSize: 14,
    fontWeight: "900",
  },
  progressTrack: {
    height: 10,
    backgroundColor: "#15223D",
    borderRadius: 5,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#1E2C4A",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#38BDF8",
    borderRadius: 5,
  },
  graphCard: {
    backgroundColor: "#111C35",
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: "#1E2C4A",
    marginBottom: 26,
  },
  graphSubHeading: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 1.2,
    marginBottom: 20,
  },
  barsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    height: 120,
    paddingHorizontal: 8,
  },
  barColumn: {
    alignItems: "center",
    flex: 1,
    height: "100%",
    justifyContent: "flex-end",
  },
  barTrackArea: {
    height: 90,
    width: 34,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  graphPillBar: {
    width: 34,
    borderRadius: 17,
  },
  graphPillBarNormal: {
    backgroundColor: "#1C2943",
  },
  graphPillBarHighest: {
    backgroundColor: "#00D2FF",
    shadowColor: "#00D2FF",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 10,
    elevation: 8,
  },
  gameLabelText: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 10,
  },
  gameLabelTextHighest: {
    color: "#38BDF8",
    fontWeight: "900",
  },
  teamCardContainer: {
    backgroundColor: "#111C35",
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: "#1E2C4A",
  },
  teamHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  groupIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#1A2846",
    justifyContent: "center",
    alignItems: "center",
  },
  groupIconImage: {
    width: 24,
    height: 24,
    tintColor: "#FFFFFF",
  },
  teamNameText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    marginLeft: 14,
  },
  coachSectionWrapper: {
    marginBottom: 18,
  },
  coachLabelHeader: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  coachInnerCard: {
    backgroundColor: "#0B1327",
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#182542",
  },
  coachAvatarWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#1B2A48",
    justifyContent: "center",
    alignItems: "center",
  },
  coachAvatarImage: {
    width: 22,
    height: 22,
    tintColor: "#FFFFFF",
  },
  coachInfoTextGroup: {
    marginLeft: 12,
  },
  coachNameText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  coachRoleText: {
    color: "#94A3B8",
    fontSize: 12,
    marginTop: 1,
  },
  viewTeamButton: {
    backgroundColor: "#152441",
    borderWidth: 1,
    borderColor: "#25375B",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  viewTeamButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  noTeamContainer: {
    paddingVertical: 12,
    alignItems: "center",
  },
  noTeamTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 4,
  },
  noTeamSubtext: {
    color: "#94A3B8",
    fontSize: 12,
    textAlign: "center",
    marginBottom: 16,
  },
  joinTeamButton: {
    backgroundColor: "#00A3FF",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: "100%",
    alignItems: "center",
  },
  joinTeamButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  devTestButton: {
    marginTop: 10,
    backgroundColor: "#111C35",
    borderWidth: 1,
    borderColor: "#38BDF8",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    width: "100%",
    alignItems: "center",
  },
  devTestButtonText: {
    color: "#38BDF8",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  skeletonPill: {
    backgroundColor: "#16233E",
    borderRadius: 8,
  },
  skeletonCard: {
    backgroundColor: "#132039",
    opacity: 0.7,
  },
});

export default styles;
