import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0B132B",
  },
  headerBar: {
    paddingTop: 60,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: "#0B132B",
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  backButton: {
    padding: 4,
    marginRight: 16,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    paddingBottom: 40,
  },
  mainTeamCard: {
    backgroundColor: "#111C35",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 20,
    alignItems: "center",
    marginBottom: 16,
  },
  avatarBox: {
    width: 84,
    height: 84,
    borderRadius: 18,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  teamTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 14,
  },
  quoteBlock: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  verticalCyanLine: {
    width: 3,
    height: "100%",
    backgroundColor: "#38BDF8",
    marginRight: 10,
    borderRadius: 2,
  },
  quoteText: {
    color: "#94A3B8",
    fontSize: 12,
    fontStyle: "italic",
    lineHeight: 18,
    flex: 1,
  },
  statsCardContainer: {
    backgroundColor: "#111C35",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 14,
    marginBottom: 24,
  },
  statColumn: {
    alignItems: "center",
    flex: 1,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: "#1E293B",
  },
  statLabel: {
    color: "#38BDF8",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  statValue: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  coachCard: {
    backgroundColor: "#111C35",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
    overflow: "hidden",
  },
  coachBannerArea: {
    height: 140,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  coachDetailsBody: {
    padding: 16,
    alignItems: "center",
  },
  coachName: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  coachRole: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 10,
  },
  experiencePill: {
    backgroundColor: "#1E293B",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 14,
  },
  experiencePillText: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "600",
  },
  viewCoachButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingVertical: 12,
    width: "100%",
    alignItems: "center",
  },
  viewCoachButtonText: {
    color: "#0B132B",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  viewAllText: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  playerCard: {
    backgroundColor: "#111C35",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  playerAvatarBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  playerInfo: {
    flex: 1,
  },
  playerName: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  positionBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#1E293B",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  positionBadgeText: {
    color: "#38BDF8",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
});

export default styles;
