import { StyleSheet, Platform } from 'react-native';

const fontPlatform = Platform.select({
  ios: 'System',
  android: 'sans-serif-medium',
  default: 'sans-serif',
});

const fontBoldPlatform = Platform.select({
  ios: 'System',
  android: 'sans-serif-medium',
  default: 'sans-serif',
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#070D19',
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 8,
    backgroundColor: '#070D19',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  headerTitleBox: {
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
  },
  headerSubtitle: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 1,
    letterSpacing: 0.5,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerBadgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 200, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0, 200, 255, 0.25)',
  },
  headerBadgePillText: {
    color: '#00C8FF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 100,
  },
  tabsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 8,
    marginBottom: 2,
  },
  tabButton: {
    paddingVertical: 5,
    paddingHorizontal: 13,
    borderRadius: 16,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#1E293B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: 'rgba(0, 200, 255, 0.15)',
    borderColor: '#00C8FF',
  },
  tabText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#94A3B8',
  },
  tabTextActive: {
    color: '#00C8FF',
    fontWeight: '800',
  },
  searchFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1E293B',
    paddingHorizontal: 10,
    height: 36,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 12,
    paddingVertical: 0,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#1E293B',
    gap: 6,
  },
  filterButtonActive: {
    backgroundColor: 'rgba(0, 200, 255, 0.15)',
    borderColor: '#00C8FF',
  },
  filterBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#00C8FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadgeText: {
    color: '#070D19',
    fontSize: 10,
    fontWeight: '900',
  },

  leaderboardHeaderBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  headlineText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    fontFamily: fontBoldPlatform,
  },
  subtext: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  columnLabel: {
    color: '#00C8FF',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  leaderboardRow: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1E293B',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  leaderboardRowTop1: {
    borderColor: 'rgba(255, 215, 0, 0.4)',
    backgroundColor: 'rgba(255, 215, 0, 0.04)',
  },
  leaderboardRowTop2: {
    borderColor: 'rgba(192, 192, 192, 0.4)',
    backgroundColor: 'rgba(192, 192, 192, 0.04)',
  },
  leaderboardRowTop3: {
    borderColor: 'rgba(205, 127, 50, 0.4)',
    backgroundColor: 'rgba(205, 127, 50, 0.04)',
  },
  rankBadgeBox: {
    width: 30,
    alignItems: 'center',
  },
  rankBadge: {
    fontSize: 14,
    fontWeight: '900',
    color: '#64748B',
  },
  rankTopBadge1: {
    color: '#FFD700',
    fontWeight: '900',
  },
  rankTopBadge2: {
    color: '#E2E8F0',
    fontWeight: '900',
  },
  rankTopBadge3: {
    color: '#CD7F32',
    fontWeight: '900',
  },
  athleteInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    marginRight: 8,
  },
  avatarCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: '#334155',
    justifyContent: 'center',
    alignItems: 'center',
  },
  athleteName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    fontFamily: fontPlatform,
  },
  athleteLocation: {
    color: '#94A3B8',
    fontSize: 11,
    marginTop: 2,
  },
  coachBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  coachBadgeText: {
    color: '#10B981',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  statValueCol: {
    alignItems: 'flex-end',
  },
  mainScoreText: {
    color: '#00C8FF',
    fontSize: 15,
    fontWeight: '900',
    fontFamily: fontBoldPlatform,
  },
  secondaryScoreText: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  paginationRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 20,
  },
  pagePill: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pagePillActive: {
    backgroundColor: '#00C8FF',
    borderColor: '#00C8FF',
  },
  pagePillText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '700',
  },
  pagePillTextActive: {
    color: '#070D19',
    fontWeight: '900',
  },
  emptyStateBox: {
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  emptyStateText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
  },
  resetButton: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: '#00C8FF',
  },
  resetButtonText: {
    color: '#00C8FF',
    fontSize: 12,
    fontWeight: '800',
  },
});

export default styles;
