import { StyleSheet, Platform } from 'react-native';

const fontPlatform = Platform.select({
  ios: 'System',
  android: 'sans-serif-medium',
  default: 'sans-serif',
});

const fontBoldPlatform = Platform.select({
  ios: 'System',
  android: 'sans-serif-black',
  default: 'sans-serif',
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#070D19',
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: '#070D19',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  closeButton: {
    padding: 4,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  imagePlaceholderBox: {
    width: '100%',
    height: 260,
    backgroundColor: '#162032',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1E293B',
    marginTop: 12,
    marginBottom: 16,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  noImageText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  crossLine1: {
    position: 'absolute',
    width: '140%',
    height: 1,
    backgroundColor: '#1E293B',
    transform: [{ rotate: '32deg' }],
  },
  crossLine2: {
    position: 'absolute',
    width: '140%',
    height: 1,
    backgroundColor: '#1E293B',
    transform: [{ rotate: '-32deg' }],
  },
  athleteNameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  athleteNameText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    fontFamily: fontBoldPlatform,
    letterSpacing: 0.5,
  },
  positionBadge: {
    borderWidth: 1,
    borderColor: '#64748B',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  positionBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  sublineRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sublineText: {
    color: '#94A3B8',
    fontSize: 13,
  },
  sportTagBadge: {
    backgroundColor: '#1E293B',
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  sportTagBadgeText: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  biometricsCard: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1E293B',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    marginBottom: 20,
  },
  biometricCol: {
    flex: 1,
    alignItems: 'center',
  },
  biometricLabel: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 4,
  },
  biometricValue: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    fontFamily: fontBoldPlatform,
  },
  biometricDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#1E293B',
  },
  sectionTitle: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 10,
  },
  analyticsGrid: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 18,
  },
  analyticBox: {
    flex: 1,
    backgroundColor: '#0F172A',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1E293B',
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  analyticValue: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    fontFamily: fontBoldPlatform,
    marginBottom: 2,
  },
  analyticLabel: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '800',
  },
  efficiencyContainer: {
    marginBottom: 20,
  },
  efficiencyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  efficiencyTitle: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  efficiencyValueText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  progressBarTrack: {
    width: '100%',
    height: 6,
    backgroundColor: '#1E293B',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 3,
  },
  contactCard: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 14,
    marginBottom: 20,
    gap: 12,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  contactText: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: fontPlatform,
  },
  scoutButton: {
    backgroundColor: '#1D4ED8',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 20,
  },
  scoutButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 1.5,
  },
  // Success Confirmation Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successCard: {
    width: '100%',
    backgroundColor: '#22C55E',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  checkmarkCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  successTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.5,
    fontFamily: fontBoldPlatform,
    textAlign: 'center',
    marginBottom: 8,
  },
  successSubtitle: {
    color: '#FFFFFF',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 24,
    opacity: 0.9,
  },
  successCloseBtn: {
    width: '100%',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCloseBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 1,
  },
});

export default styles;
