import { StyleSheet, Platform } from 'react-native';

const fontPlatform = Platform.select({
  ios: 'System',
  android: 'sans-serif-medium',
  default: 'sans-serif',
});

const fontBoldPlatform = Platform.select({
  ios: 'System',
  android: 'sans-serif-black',
  default: 'sans-serif',
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#070D19',
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 10,
    backgroundColor: '#070D19',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 21,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 120,
  },
  sectionTitle: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginTop: 12,
    marginBottom: 8,
  },
  matchResultCard: {
    backgroundColor: '#0F172A',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#00C8FF',
    padding: 20,
    alignItems: 'center',
    marginBottom: 16,
  },
  teamIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
    marginBottom: 6,
  },
  winBadgeBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#052E16',
    borderWidth: 1.5,
    borderColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 4,
  },
  winBadgeLetter: {
    color: '#34D399',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  lossBadgeBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#450A0A',
    borderWidth: 1.5,
    borderColor: '#EF4444',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
  },
  lossBadgeLetter: {
    color: '#F87171',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  teamName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  teamRoleText: {
    color: '#94A3B8',
    fontSize: 11,
    marginTop: 1,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 4,
  },
  scoreHomeText: {
    color: '#00C8FF',
    fontSize: 24,
    fontWeight: '900',
  },
  scoreAwayText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
  },
  vsText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '800',
  },
  tableCard: {
    backgroundColor: '#0F172A',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 16,
    marginBottom: 16,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
    paddingBottom: 10,
    marginBottom: 8,
  },
  tableHeaderLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  playerBadge: {
    minWidth: 32,
    height: 26,
    paddingHorizontal: 4,
    borderRadius: 6,
    backgroundColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
  },
  rankBadge1st: {
    backgroundColor: 'rgba(245, 158, 11, 0.18)',
    borderColor: '#F59E0B',
  },
  rankBadge2nd: {
    backgroundColor: 'rgba(148, 163, 184, 0.18)',
    borderColor: '#94A3B8',
  },
  rankBadge3rd: {
    backgroundColor: 'rgba(217, 119, 6, 0.18)',
    borderColor: '#D97706',
  },
  rankText1st: {
    color: '#F59E0B',
    fontWeight: '900',
  },
  rankText2nd: {
    color: '#E2E8F0',
    fontWeight: '900',
  },
  rankText3rd: {
    color: '#FBBF24',
    fontWeight: '900',
  },
  playerName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    fontFamily: fontPlatform,
  },
  ptsValue: {
    color: '#00C8FF',
    fontSize: 14,
    fontWeight: '900',
  },
  astValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  dynamicsCard: {
    backgroundColor: '#0F172A',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 16,
    marginBottom: 20,
  },
  teamSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(0, 200, 255, 0.08)',
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderLeftWidth: 3,
    borderLeftColor: '#00C8FF',
    marginVertical: 6,
  },
  teamSectionHeaderText: {
    color: '#00C8FF',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  outcomePillBadge: {
    minWidth: 28,
    height: 22,
    paddingHorizontal: 4,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  outcomeBadgeWin: {
    backgroundColor: 'rgba(16, 185, 129, 0.18)',
    borderColor: '#10B981',
  },
  outcomeBadgeLoss: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
    borderColor: '#EF4444',
  },
  outcomeBadgeTie: {
    backgroundColor: 'rgba(148, 163, 184, 0.15)',
    borderColor: '#64748B',
  },
  outcomeBadge1st: {
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    borderColor: '#F59E0B',
  },
  outcomeBadge2nd: {
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    borderColor: '#94A3B8',
  },
  outcomeBadge3rd: {
    backgroundColor: 'rgba(217, 119, 6, 0.2)',
    borderColor: '#D97706',
  },
  outcomePillText: {
    fontSize: 11,
    fontWeight: '900',
  },
});

export default styles;
