import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  popoverShell: {
    position: 'absolute',
    top: '56px',
    right: '28px',
    width: '360px',
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    boxShadow: 'none',
    zIndex: 1000,
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
  },
  popoverHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 18px',
    borderBottom: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
  },
  headerTitle: {
    fontSize: '13.5px',
    fontWeight: 700,
    letterSpacing: '0.06em',
    color: '#1E293B',
    margin: 0,
    textTransform: 'uppercase',
  },
  markAllBtn: {
    background: 'none',
    border: 'none',
    fontSize: '13px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    color: '#006699',
    cursor: 'pointer',
    padding: 0,
    textTransform: 'uppercase',
  },
  itemsList: {
    maxHeight: '400px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  itemRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    padding: '16px 18px',
    borderBottom: '1px solid #E2E8F0',
    backgroundColor: '#FFFFFF',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  itemRowNoBorder: {
    borderBottom: 'none',
  },
  badgeAudit: {
    width: '38px',
    height: '38px',
    backgroundColor: '#18223B',
    color: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    borderRadius: '1px',
  },
  badgeSchedule: {
    width: '38px',
    height: '38px',
    backgroundColor: '#E2E8F0',
    border: '1.5px solid #0B132B',
    color: '#0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    borderRadius: '1px',
  },
  itemContent: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '6px',
  },
  pillAudit: {
    border: '1.5px solid #18223B',
    backgroundColor: '#FFFFFF',
    padding: '2px 7px',
    fontSize: '9.5px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#18223B',
    textTransform: 'uppercase',
  },
  pillSchedule: {
    border: '1.5px solid #94A3B8',
    backgroundColor: '#FFFFFF',
    padding: '2px 7px',
    fontSize: '9.5px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#334155',
    textTransform: 'uppercase',
  },
  timestamp: {
    fontSize: '11px',
    fontWeight: 500,
    color: '#64748B',
    letterSpacing: '0.02em',
  },
  itemTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#18223B',
    margin: '2px 0 0 0',
    lineHeight: 1.35,
  },
  itemSubtext: {
    fontSize: '11.5px',
    color: '#64748B',
    margin: '4px 0 0 0',
    lineHeight: 1.45,
  },
  footerContainer: {
    padding: '14px 16px 16px 16px',
    borderTop: '1px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    boxSizing: 'border-box',
  },
  footerBtn: {
    backgroundColor: '#18223B',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 16px',
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.14em',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    textTransform: 'uppercase',
    width: '100%',
    borderRadius: '1px',
    boxSizing: 'border-box',
  },
  emptyState: {
    padding: '36px 18px',
    textAlign: 'center',
    color: '#94A3B8',
    fontSize: '12px',
    fontStyle: 'italic',
  },
};
