import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  layoutBody: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 58px)',
    overflow: 'hidden',
  },
  contentArea: {
    flex: 1,
    padding: '28px 36px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '28px',
  },
  titleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  pageTitle: {
    fontSize: '28px',
    fontWeight: 900,
    letterSpacing: '0.02em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  pageSubtitle: {
    fontSize: '13px',
    color: '#64748B',
    margin: 0,
  },
  goBackBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'none',
    border: 'none',
    color: '#0B132B',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
    padding: '4px 8px',
  },
  filterBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #E2E8F0',
    marginBottom: '24px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  tabList: {
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
  },
  tabBtn: {
    background: 'none',
    border: 'none',
    padding: '10px 0',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#64748B',
    cursor: 'pointer',
    textTransform: 'uppercase',
    position: 'relative',
    borderBottom: '3px solid transparent',
  },
  tabBtnActive: {
    color: '#0B132B',
    borderBottom: '3px solid #0B132B',
  },
  actionBtnGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  outlineBtn: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    color: '#0B132B',
    padding: '7px 14px',
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.06em',
    cursor: 'pointer',
    textTransform: 'uppercase',
    transition: 'background-color 0.15s ease',
  },
  solidBtn: {
    backgroundColor: '#0B132B',
    border: '2px solid #0B132B',
    color: '#FFFFFF',
    padding: '7px 14px',
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.06em',
    cursor: 'pointer',
    textTransform: 'uppercase',
    transition: 'background-color 0.15s ease',
  },
  feedList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },

  /* Audit Request Card */
  auditCard: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '18px 22px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  cardTopLine: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  auditCardTitle: {
    fontSize: '13px',
    fontWeight: 900,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  cardTimestamp: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#64748B',
  },
  auditGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
    padding: '4px 0',
  },
  gridCol: {
    borderLeft: '2px solid #0B132B',
    paddingLeft: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  gridColLabel: {
    fontSize: '9.5px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  gridColVal: {
    fontSize: '12px',
    fontWeight: 900,
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  auditActionBtn: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    color: '#0B132B',
    padding: '8px 16px',
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.06em',
    cursor: 'pointer',
    textTransform: 'uppercase',
    marginTop: '4px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },

  /* Schedule Updates Card */
  scheduleCard: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '18px 22px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  scheduleTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  scheduleHeaderTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 900,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  squareBullet: {
    width: '7px',
    height: '7px',
    backgroundColor: '#0B132B',
    display: 'inline-block',
  },
  scheduleDivider: {
    borderTop: '1px solid #0B132B',
    margin: 0,
  },
  scheduleDescription: {
    fontSize: '12px',
    color: '#0B132B',
    lineHeight: 1.5,
    margin: 0,
  },
  scheduleActionsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginTop: '2px',
  },
  viewDetailsLink: {
    fontSize: '11px',
    fontWeight: 900,
    color: '#0B132B',
    textDecoration: 'underline',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    textTransform: 'uppercase',
  },
  dismissLink: {
    fontSize: '11px',
    fontWeight: 800,
    color: '#64748B',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    textTransform: 'uppercase',
  },

  emptyStateWrap: {
    border: '2px dashed #CBD5E1',
    padding: '48px 24px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    color: '#64748B',
  },
};
