import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  },
  header: {
    height: '64px',
    borderBottom: '1.5px solid #0F172A',
    padding: '0 40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
  },
  logo: {
    fontSize: '22px',
    fontWeight: '900',
    letterSpacing: '0.15em',
    color: '#0F172A',
    textDecoration: 'none',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    fontSize: '15px',
    fontWeight: '800',
    letterSpacing: '0.08em',
    color: '#0F172A',
  },
  profileIcon: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
  },
  layout: {
    display: 'flex',
    flex: 1,
  },
  sidebar: {
    width: '240px',
    borderRight: '1.5px solid #0F172A',
    paddingTop: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    backgroundColor: '#FFFFFF',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 24px',
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.1em',
    color: '#64748B',
    textDecoration: 'none',
    cursor: 'pointer',
    borderLeft: '4px solid transparent',
  },
  navItemActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 24px',
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.1em',
    color: '#0F172A',
    backgroundColor: '#E2E8F0',
    textDecoration: 'none',
    borderLeft: '4px solid #0F172A',
  },
  main: {
    flex: 1,
    padding: '36px 48px',
    backgroundColor: '#FFFFFF',
  },
  titleRow: {
    marginBottom: '28px',
  },
  title: {
    fontSize: '26px',
    fontWeight: '900',
    letterSpacing: '0.04em',
    color: '#0F172A',
    margin: '0 0 10px 0',
    textTransform: 'uppercase',
  },
  badgeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  pendingBadge: {
    backgroundColor: '#0F172A',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '0.15em',
    padding: '5px 12px',
    borderRadius: '4px',
  },
  statusText: {
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.15em',
    color: '#64748B',
    fontFamily: 'monospace',
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 280px',
    gap: '24px',
    marginBottom: '32px',
  },
  criticalCard: {
    border: '1.5px solid #0F172A',
    padding: '24px 28px',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: '140px',
  },
  criticalTitle: {
    fontSize: '15px',
    fontWeight: '900',
    letterSpacing: '0.06em',
    color: '#0F172A',
    margin: '0 0 8px 0',
    textTransform: 'uppercase',
  },
  criticalText: {
    fontSize: '12px',
    lineHeight: '1.6',
    color: '#334155',
    margin: '0 0 16px 0',
    maxWidth: '480px',
    fontWeight: '500',
  },
  batchBtn: {
    alignSelf: 'flex-start',
    backgroundColor: '#0F172A',
    color: '#FFFFFF',
    border: 'none',
    padding: '10px 18px',
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.12em',
    cursor: 'pointer',
    borderRadius: '2px',
    textTransform: 'uppercase',
  },
  watermark: {
    position: 'absolute',
    right: '-10px',
    top: '10px',
    fontSize: '120px',
    fontWeight: '900',
    color: '#F1F5F9',
    userSelect: 'none',
    pointerEvents: 'none',
    lineHeight: 1,
  },
  healthCard: {
    backgroundColor: '#0F172A',
    color: '#FFFFFF',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  healthLabel: {
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '0.15em',
    color: '#94A3B8',
    textTransform: 'uppercase',
    fontFamily: 'monospace',
  },
  healthValue: {
    fontSize: '44px',
    fontWeight: '900',
    letterSpacing: '-0.02em',
    margin: '8px 0',
    color: '#FFFFFF',
  },
  healthSub: {
    fontSize: '9px',
    fontWeight: '700',
    letterSpacing: '0.15em',
    color: '#94A3B8',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
  },
  tableContainer: {
    border: '1.5px solid #0F172A',
    marginBottom: '24px',
    backgroundColor: '#FFFFFF',
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    backgroundColor: '#F1F5F9',
    color: '#0F172A',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '0.12em',
    padding: '14px 18px',
    borderBottom: '1.5px solid #0F172A',
    borderRight: '1px solid #E2E8F0',
    textTransform: 'uppercase',
  },
  td: {
    padding: '14px 18px',
    fontSize: '12px',
    color: '#0F172A',
    borderBottom: '1px solid #E2E8F0',
    borderRight: '1px solid #E2E8F0',
    fontWeight: '600',
  },
  idText: {
    fontFamily: 'monospace',
    fontWeight: '700',
    fontSize: '12px',
    color: '#0F172A',
  },
  dateText: {
    fontFamily: 'monospace',
    fontSize: '12px',
    color: '#334155',
  },
  pendingReviewBadge: {
    display: 'inline-block',
    border: '1px solid #EF4444',
    color: '#DC2626',
    backgroundColor: '#FEF2F2',
    padding: '4px 8px',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '0.08em',
    borderRadius: '2px',
    fontFamily: 'monospace',
  },
  verifiedBadge: {
    display: 'inline-block',
    backgroundColor: '#0F172A',
    color: '#FFFFFF',
    padding: '4px 10px',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '0.08em',
    borderRadius: '2px',
    fontFamily: 'monospace',
  },
  auditBtn: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #0F172A',
    color: '#0F172A',
    padding: '5px 14px',
    fontSize: '10px',
    fontWeight: '900',
    letterSpacing: '0.12em',
    cursor: 'pointer',
    borderRadius: '2px',
  },
  paginationRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  pageArrowBtn: {
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1.5px solid #0F172A',
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '800',
  },
  pageNumberBtn: {
    height: '36px',
    padding: '0 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0F172A',
    color: '#FFFFFF',
    border: 'none',
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.1em',
    cursor: 'pointer',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: '16px',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    width: '100%',
    maxWidth: '520px',
    borderRadius: '8px',
    border: '2px solid #0F172A',
    padding: '28px',
    boxShadow: '0 20px 25px -5px rgba(0,0,0,0.2)',
  },
};
