import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  layout: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 64px)',
    overflow: 'hidden',
  },
  main: {
    flex: 1,
    padding: '36px 48px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    height: '100%',
    scrollbarGutter: 'stable',
    boxSizing: 'border-box',
  },
  titleRow: {
    marginBottom: '8px',
  },
  title: {
    fontSize: '32px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    color: '#0B132B',
    margin: '0 0 12px 0',
    textTransform: 'uppercase',
  },
  badgeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    marginBottom: '28px',
  },
  pendingBadge: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    padding: '4px 10px',
    borderRadius: '2px',
    textTransform: 'uppercase',
  },
  statusText: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.12em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 240px',
    gap: '20px',
    marginBottom: '28px',
  },
  criticalCard: {
    border: '1.5px solid #0B132B',
    borderRadius: '2px',
    padding: '24px 28px',
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    minHeight: '120px',
    boxSizing: 'border-box',
  },
  watermark: {
    position: 'absolute',
    right: '20px',
    top: '50%',
    transform: 'translateY(-50%)',
    opacity: 0.07,
    pointerEvents: 'none',
  },
  criticalTitle: {
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.06em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  criticalText: {
    fontSize: '12.5px',
    lineHeight: '1.6',
    color: '#475569',
    maxWidth: '620px',
    margin: '4px 0 0 0',
  },
  healthCard: {
    backgroundColor: '#0B132B',
    borderRadius: '2px',
    padding: '22px 24px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    color: '#FFFFFF',
    minHeight: '140px',
    boxSizing: 'border-box',
  },
  healthLabel: {
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.1em',
    color: '#94A3B8',
    textTransform: 'uppercase',
  },
  liveIndicatorDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
    boxShadow: '0 0 8px #10B981',
    display: 'inline-block',
  },
  healthValue: {
    fontSize: '36px',
    fontWeight: 900,
    letterSpacing: '-0.03em',
    lineHeight: 1,
    margin: '8px 0 4px 0',
    color: '#FFFFFF',
  },
  healthSub: {
    fontSize: '9.5px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#34D399',
    textTransform: 'uppercase',
  },
  healthFooter: {
    fontSize: '8.5px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#94A3B8',
    borderTop: '1px solid rgba(255, 255, 255, 0.12)',
    paddingTop: '8px',
    marginTop: '6px',
    textTransform: 'uppercase',
  },
  tableContainer: {
    border: '1.5px solid #0B132B',
    borderRadius: '2px',
    overflow: 'hidden',
    marginBottom: '20px',
    backgroundColor: '#FFFFFF',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    tableLayout: 'fixed',
  },
  th: {
    backgroundColor: '#E2E8F0',
    color: '#0B132B',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    padding: '12px 18px',
    height: '44px',
    borderBottom: '1.5px solid #0B132B',
    borderRight: '1.5px solid #0B132B',
    textTransform: 'uppercase',
    boxSizing: 'border-box',
  },
  td: {
    padding: '12px 18px',
    fontSize: '13px',
    borderBottom: '1.5px solid #0B132B',
    borderRight: '1.5px solid #0B132B',
    color: '#0B132B',
    verticalAlign: 'middle',
    boxSizing: 'border-box',
    height: '50px',
  },
  trClickable: {
    cursor: 'pointer',
    transition: 'background-color 0.12s ease',
  },
  idText: {
    fontFamily: 'monospace',
    fontWeight: 800,
    fontSize: '12px',
    letterSpacing: '0.05em',
  },
  affiliationText: {
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  dateText: {
    fontFamily: 'monospace',
    fontSize: '12px',
    color: '#334155',
  },
  pendingReviewBadge: {
    display: 'inline-block',
    border: '1px solid #EF4444',
    color: '#EF4444',
    backgroundColor: '#FEF2F2',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '3px 8px',
    borderRadius: '2px',
    textTransform: 'uppercase',
  },
  verifiedBadge: {
    display: 'inline-block',
    border: '1px solid #16A34A',
    color: '#16A34A',
    backgroundColor: '#F0FDF4',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '3px 8px',
    borderRadius: '2px',
    textTransform: 'uppercase',
  },
  auditBtn: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #0B132B',
    borderRadius: '2px',
    color: '#0B132B',
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    padding: '6px 14px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    textTransform: 'uppercase',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    minWidth: '64px',
  },
  paginationRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: '16px',
  },
  pageArrowBtn: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    borderRadius: '2px',
  },
  pageNumberBtn: {
    backgroundColor: '#0B132B',
    border: '1.5px solid #0B132B',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '0 16px',
    height: '32px',
    borderRadius: '2px',
    cursor: 'default',
  },
};
