import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.65)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    backdropFilter: 'blur(3px)',
    padding: '24px',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    borderRadius: '4px',
    width: '100%',
    maxWidth: '740px',
    maxHeight: '90vh',
    overflowY: 'auto',
    padding: '32px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.35)',
    boxSizing: 'border-box',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1.5px solid #CBD5E1',
    paddingBottom: '16px',
    marginBottom: '20px',
  },
  modalTitle: {
    fontSize: '16px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#64748B',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifiedBanner: {
    backgroundColor: '#DCFCE7',
    border: '1px solid #16A34A',
    color: '#15803D',
    fontSize: '12px',
    fontWeight: 800,
    padding: '10px 14px',
    borderRadius: '3px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '16px',
  },
  coachBioGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '14px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    padding: '16px 20px',
    borderRadius: '4px',
    marginBottom: '20px',
  },
  bioItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  bioLabel: {
    fontSize: '10px',
    fontWeight: 800,
    color: '#64748B',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  bioValue: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#0B132B',
  },
  pendingReviewBadge: {
    display: 'inline-block',
    border: '1px solid #EF4444',
    color: '#EF4444',
    backgroundColor: '#FEF2F2',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '3px 8px',
    borderRadius: '2px',
    textTransform: 'uppercase',
  },
  verifiedBadge: {
    display: 'inline-block',
    border: '1px solid #16A34A',
    color: '#16A34A',
    backgroundColor: '#F0FDF4',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '3px 8px',
    borderRadius: '2px',
    textTransform: 'uppercase',
  },
  docSectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
    marginBottom: '12px',
  },
  docList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '12px',
    marginBottom: '24px',
  },
  docCard: {
    border: '1px solid #CBD5E1',
    borderRadius: '4px',
    padding: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
  },
  docInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  docMeta: {
    fontSize: '10px',
    color: '#64748B',
  },
  docName: {
    fontSize: '12px',
    fontWeight: 800,
    color: '#0B132B',
  },
  docViewBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    fontWeight: 800,
    color: '#0B132B',
    textDecoration: 'none',
    padding: '5px 10px',
    border: '1px solid #CBD5E1',
    borderRadius: '3px',
    backgroundColor: '#F8FAFC',
    cursor: 'pointer',
  },
  noDocBox: {
    border: '1px dashed #CBD5E1',
    padding: '24px',
    textAlign: 'center',
    fontSize: '12px',
    color: '#64748B',
    borderRadius: '4px',
    marginBottom: '24px',
  },
  modalActions: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
    borderTop: '1.5px solid #CBD5E1',
    paddingTop: '20px',
  },
  declineBtn: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #DC2626',
    color: '#DC2626',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '10px 20px',
    borderRadius: '3px',
    cursor: 'pointer',
    textTransform: 'uppercase',
  },
  approveBtn: {
    backgroundColor: '#0B132B',
    border: '1.5px solid #0B132B',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '10px 22px',
    borderRadius: '3px',
    cursor: 'pointer',
    textTransform: 'uppercase',
  },
};
