import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  layout: {
    display: 'flex',
    flex: 1,
    minHeight: 'calc(100vh - 64px)',
  },
  main: {
    flex: 1,
    padding: '36px 48px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    boxSizing: 'border-box',
  },
  titleRow: {
    marginBottom: '8px',
  },
  title: {
    fontSize: '32px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    color: '#0B132B',
    margin: '0 0 12px 0',
    textTransform: 'uppercase',
  },
  badgeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  pendingBadge: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    padding: '4px 10px',
    borderRadius: '2px',
    textTransform: 'uppercase',
  },
  statusText: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.12em',
    color: '#64748B',
    textTransform: 'uppercase',
  },

  /* Top Cards Grid */
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 280px',
    gap: '24px',
    marginTop: '28px',
    marginBottom: '32px',
  },
  criticalCard: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '24px 32px',
    position: 'relative',
    overflow: 'hidden',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    minHeight: '140px',
  },
  watermark: {
    position: 'absolute',
    top: '-15px',
    right: '10px',
    pointerEvents: 'none',
    opacity: 0.12,
  },
  criticalTitle: {
    fontSize: '18px',
    fontWeight: 900,
    color: '#0B132B',
    margin: '0 0 10px 0',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  criticalText: {
    fontSize: '13px',
    color: '#475569',
    lineHeight: 1.6,
    margin: 0,
    maxWidth: '620px',
    fontWeight: 500,
  },

  healthCard: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '24px 28px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    boxSizing: 'border-box',
    border: '1.5px solid #0B132B',
    minHeight: '140px',
  },
  healthLabel: {
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.15em',
    color: '#94A3B8',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
  },
  healthValue: {
    fontSize: '44px',
    fontWeight: 900,
    color: '#FFFFFF',
    margin: '2px 0',
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
  },
  healthSub: {
    fontSize: '10px',
    fontWeight: 700,
    letterSpacing: '0.18em',
    color: '#CBD5E1',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
  },

  /* Data Table */
  tableContainer: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    marginBottom: '24px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    backgroundColor: '#ECEFF1',
    color: '#0B132B',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    padding: '14px 18px',
    borderBottom: '1.5px solid #0B132B',
    borderRight: '1.5px solid #0B132B',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '14px 18px',
    fontSize: '12px',
    color: '#0B132B',
    borderBottom: '1.5px solid #0B132B',
    borderRight: '1.5px solid #0B132B',
    verticalAlign: 'middle',
  },
  idText: {
    fontFamily: 'monospace',
    fontWeight: 700,
    fontSize: '12px',
    color: '#0B132B',
    letterSpacing: '0.04em',
  },
  affiliationText: {
    fontFamily: 'monospace',
    fontWeight: 600,
    fontSize: '12px',
    color: '#1E293B',
    textTransform: 'uppercase',
  },
  dateText: {
    fontFamily: 'monospace',
    fontSize: '12px',
    color: '#334155',
    letterSpacing: '0.02em',
  },
  pendingReviewBadge: {
    border: '1px solid #EF4444',
    backgroundColor: '#FFFFFF',
    color: '#EF4444',
    fontSize: '10px',
    fontWeight: 800,
    padding: '3px 8px',
    letterSpacing: '0.06em',
    display: 'inline-block',
    textTransform: 'uppercase',
  },
  verifiedBadge: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    padding: '3px 8px',
    letterSpacing: '0.06em',
    display: 'inline-block',
    textTransform: 'uppercase',
  },
  auditBtn: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #0B132B',
    color: '#0B132B',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    padding: '6px 14px',
    cursor: 'pointer',
    textTransform: 'uppercase',
    transition: 'all 0.15s ease',
  },

  /* Pagination */
  paginationRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '16px',
  },
  pageArrowBtn: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    padding: '6px 10px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.15s ease',
  },
  pageNumberBtn: {
    backgroundColor: '#0B132B',
    border: '1.5px solid #0B132B',
    color: '#FFFFFF',
    padding: '6px 16px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.1em',
    cursor: 'default',
    textTransform: 'uppercase',
  },

  /* Audit Modal Overlay & Elements */
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.65)',
    backdropFilter: 'blur(2px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    width: '92%',
    maxWidth: '680px',
    maxHeight: '90vh',
    overflowY: 'auto',
    padding: '32px',
    boxShadow: '0 25px 50px -12px rgba(11, 19, 43, 0.25)',
    boxSizing: 'border-box',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    borderBottom: '1.5px solid #0B132B',
    paddingBottom: '14px',
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 900,
    color: '#0B132B',
    margin: 0,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#64748B',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coachBioGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px 20px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    padding: '16px 20px',
    borderRadius: '4px',
    marginBottom: '24px',
  },
  bioItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  bioLabel: {
    fontSize: '10px',
    fontWeight: 800,
    color: '#64748B',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  bioValue: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#0B132B',
  },
  docSectionTitle: {
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#0B132B',
    textTransform: 'uppercase',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  docList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '28px',
  },
  docCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #CBD5E1',
    borderRadius: '4px',
    transition: 'border-color 0.15s ease',
  },
  docInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  docName: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#0B132B',
  },
  docMeta: {
    fontSize: '11px',
    color: '#64748B',
  },
  docViewBtn: {
    padding: '6px 12px',
    fontSize: '11px',
    fontWeight: 700,
    backgroundColor: '#F1F5F9',
    color: '#0B132B',
    border: '1px solid #CBD5E1',
    borderRadius: '4px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    textDecoration: 'none',
  },
  noDocBox: {
    padding: '16px',
    backgroundColor: '#F8FAFC',
    border: '1px dashed #CBD5E1',
    borderRadius: '4px',
    color: '#64748B',
    fontSize: '12px',
    textAlign: 'center',
    marginBottom: '24px',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    borderTop: '1.5px solid #E2E8F0',
    paddingTop: '20px',
  },
  declineBtn: {
    padding: '10px 18px',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid #DC2626',
    color: '#DC2626',
    fontWeight: 800,
    fontSize: '11px',
    letterSpacing: '0.08em',
    cursor: 'pointer',
    textTransform: 'uppercase',
  },
  approveBtn: {
    padding: '10px 22px',
    backgroundColor: '#0B132B',
    border: '1.5px solid #0B132B',
    color: '#FFFFFF',
    fontWeight: 800,
    fontSize: '11px',
    letterSpacing: '0.08em',
    cursor: 'pointer',
    textTransform: 'uppercase',
    transition: 'background-color 0.15s ease',
  },
  verifiedBanner: {
    padding: '12px 16px',
    backgroundColor: '#F0FDF4',
    border: '1px solid #BBF7D0',
    color: '#15803D',
    fontSize: '12px',
    fontWeight: 700,
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
};
