import { StyleSheet, Platform } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-black",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: "#070D19",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  closeButton: {
    padding: 4,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 32,
  },
  bannerTile: {
    backgroundColor: "#0D192E",
    borderRadius: 12,
    paddingVertical: 20,
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.15)",
  },
  bannerTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 1.5,
    marginBottom: 12,
    fontFamily: fontBoldPlatform,
  },
  averagesTopRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  averagesTopCard: {
    flex: 1,
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  avgLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#64748B",
    letterSpacing: 1,
  },
  avgValueLarge: {
    fontSize: 28,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 6,
    fontFamily: fontBoldPlatform,
  },
  averagesBottomRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 24,
  },
  averagesSmallCard: {
    flex: 1,
    backgroundColor: "#0D192E",
    borderRadius: 14,
    padding: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  avgValueSmall: {
    fontSize: 20,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 4,
    fontFamily: fontBoldPlatform,
  },
  splitCardFull: {
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  splitCardHalfRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  splitCardHalf: {
    flex: 1,
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  splitHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  splitValueText: {
    fontSize: 26,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 8,
    fontFamily: fontBoldPlatform,
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: "#162238",
    borderRadius: 3,
    marginTop: 14,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#00C8FF",
    borderRadius: 3,
  },
  advancedTile: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#0D192E",
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  advancedLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#94A3B8",
    letterSpacing: 1,
  },
  advancedValue: {
    fontSize: 22,
    fontWeight: "900",
    color: "#FFFFFF",
    fontFamily: fontBoldPlatform,
  },

  /* WORKLOAD ANALYTICS PANEL STYLES */
  workloadSectionContainer: {
    marginTop: 16,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
  },
  acwrCard: {
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
  },
  acwrTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  acwrTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#94A3B8",
  },
  acwrScoreText: {
    fontSize: 28,
    fontWeight: "900",
    color: "#FFFFFF",
    fontFamily: fontBoldPlatform,
  },
  statusBadgeRed: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    borderColor: "#EF4444",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 10,
  },
  statusBadgeGreen: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    borderColor: "#10B981",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 10,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  acwrDescription: {
    fontSize: 12,
    color: "#CBD5E1",
    lineHeight: 18,
  },
  zoneBarContainer: {
    marginTop: 14,
  },
  zoneLabelsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  zoneText: {
    fontSize: 10,
    fontWeight: "800",
  },
  dualZoneTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#162238",
    flexDirection: "row",
    overflow: "hidden",
  },
  greenZoneFill: {
    height: "100%",
    backgroundColor: "#10B981",
  },
  redZoneFill: {
    height: "100%",
    backgroundColor: "#EF4444",
  },
  effortGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  effortCard: {
    flex: 1,
    backgroundColor: "#0D192E",
    borderRadius: 14,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  effortLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#64748B",
    letterSpacing: 0.5,
  },
  effortValueCyan: {
    fontSize: 22,
    fontWeight: "900",
    color: "#00C8FF",
    marginTop: 4,
    fontFamily: fontBoldPlatform,
  },
  effortValueWhite: {
    fontSize: 22,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 4,
    fontFamily: fontBoldPlatform,
  },
  tiles2x2Grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 20,
  },
  workloadTile: {
    width: "48%",
    backgroundColor: "#0D192E",
    borderRadius: 14,
    padding: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  targetPanelCard: {
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.2)",
    marginBottom: 20,
  },
  targetPanelTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1,
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#94A3B8",
    marginBottom: 6,
  },
  durationInput: {
    backgroundColor: "#070D19",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E293B",
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 14,
  },
  intensityPillScroll: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 16,
  },
  intensityPill: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#070D19",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  intensityPillActive: {
    backgroundColor: "#00C8FF",
    borderColor: "#00C8FF",
  },
  intensityPillText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#94A3B8",
  },
  intensityPillTextActive: {
    color: "#070D19",
  },
  logCtaButton: {
    backgroundColor: "#00C8FF",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  logCtaText: {
    fontSize: 13,
    fontWeight: "900",
    color: "#070D19",
    letterSpacing: 1,
  },
});

export default styles;
