import { StyleSheet, Platform } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: "#070D19",
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#3B82F6",
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  heroCard: {
    backgroundColor: "#0D192E",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.15)",
  },
  diamondContainer: {
    width: 90,
    height: 90,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  diamondBorder: {
    position: "absolute",
    width: 64,
    height: 64,
    borderWidth: 2,
    borderColor: "#00C8FF",
    transform: [{ rotate: "45deg" }],
    borderRadius: 8,
  },
  diamondIcon: {
    zIndex: 2,
  },
  heroName: {
    fontSize: 22,
    fontWeight: "900",
    color: "#FFFFFF",
    textAlign: "center",
    fontFamily: fontBoldPlatform,
  },
  heroBirthdate: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 4,
    fontFamily: fontPlatform,
  },
  sublineTagsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  tagBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0F172A",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#1E293B",
    gap: 4,
  },
  tagBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#CBD5E1",
    fontFamily: fontPlatform,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  viewAllLink: {
    fontSize: 11,
    fontWeight: "700",
    color: "#94A3B8",
    textDecorationLine: "underline",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    width: "48%",
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  statLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#64748B",
    letterSpacing: 1,
  },
  statValue: {
    fontSize: 24,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 6,
    fontFamily: fontBoldPlatform,
  },
  physicalPanel: {
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
    gap: 12,
  },
  physicalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  physicalLabel: {
    fontSize: 13,
    color: "#94A3B8",
    fontFamily: fontPlatform,
  },
  physicalValue: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
    fontFamily: fontBoldPlatform,
  },
  recentMatchesList: {
    gap: 10,
    marginBottom: 24,
  },
  matchRowCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0D192E",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  matchOpponentText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#CBD5E1",
  },
  matchBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  matchResultBadgeWin: {
    fontSize: 11,
    fontWeight: "900",
    color: "#00C8FF",
  },
  matchResultBadgeLoss: {
    fontSize: 11,
    fontWeight: "900",
    color: "#EF4444",
  },
  matchDateText: {
    fontSize: 11,
    color: "#64748B",
  },
  chartContainerCard: {
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.1)",
  },
  chartHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  chartTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  chartSubtext: {
    fontSize: 10,
    color: "#64748B",
  },
  docsGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  docTile: {
    flex: 1,
    backgroundColor: "#0D192E",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  docLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#FFFFFF",
    marginTop: 10,
  },
  stickyBottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: "#070D19",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
  },
  inquiryButton: {
    backgroundColor: "#00C8FF",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
  },
  inquiryButtonText: {
    fontSize: 13,
    fontWeight: "900",
    color: "#070D19",
    letterSpacing: 1,
  },
});

export default styles;
