import { StyleSheet, Platform } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: "#070D19",
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logoText: {
    fontSize: 20,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  editButton: {
    backgroundColor: "rgba(0, 200, 255, 0.12)",
    borderWidth: 1,
    borderColor: "#00C8FF",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 6,
  },
  editText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#00C8FF",
    letterSpacing: 0.5,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#F8FAFC",
    letterSpacing: 1,
    marginBottom: 16,
    fontFamily: fontBoldPlatform,
  },
  scoreBoardCard: {
    backgroundColor: "#0D1526",
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
    alignItems: "center",
  },
  teamBlock: {
    alignItems: "center",
  },
  teamIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "rgba(0, 200, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  teamName: {
    fontSize: 17,
    fontWeight: "900",
    color: "#F8FAFC",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
    textAlign: "center",
  },
  teamSubtext: {
    fontSize: 10,
    fontWeight: "800",
    color: "#00C8FF",
    letterSpacing: 1,
    marginTop: 3,
  },
  vsScoreRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    marginVertical: 14,
  },
  scoreTextLarge: {
    fontSize: 44,
    fontWeight: "900",
    color: "#FFFFFF",
    fontFamily: fontBoldPlatform,
  },
  vsText: {
    fontSize: 16,
    fontWeight: "900",
    color: "#64748B",
    letterSpacing: 2,
  },
  statusSubline: {
    borderTopWidth: 1,
    borderTopColor: "#1E293B",
    width: "100%",
    paddingTop: 14,
    marginTop: 8,
    alignItems: "center",
  },
  statusLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#64748B",
    letterSpacing: 1,
  },
  statusValue: {
    fontSize: 12,
    fontWeight: "900",
    color: "#00C8FF",
    marginTop: 2,
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#F8FAFC",
    marginBottom: 12,
    fontFamily: fontBoldPlatform,
  },
  tableCard: {
    backgroundColor: "#0D1526",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#111C33",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  colNameHeader: {
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    color: "#94A3B8",
    letterSpacing: 1,
  },
  colStatHeader: {
    width: 44,
    fontSize: 11,
    fontWeight: "800",
    color: "#94A3B8",
    textAlign: "center",
    letterSpacing: 1,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  nameText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#F8FAFC",
    fontFamily: fontBoldPlatform,
  },
  statValueText: {
    width: 44,
    fontSize: 13,
    fontWeight: "700",
    color: "#38BDF8",
    textAlign: "center",
  },
  coachNotesCard: {
    backgroundColor: "#0D1526",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  coachNotesTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 1,
    marginBottom: 12,
  },
  noteRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    marginBottom: 8,
  },
  noteIndex: {
    fontSize: 12,
    fontWeight: "900",
    color: "#00C8FF",
  },
  noteContentText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
    color: "#E2E8F0",
    lineHeight: 18,
  },
  noteSkeleton1: {
    height: 8,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 4,
    width: "85%",
    marginTop: 4,
  },
  noteSkeleton2: {
    height: 8,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 4,
    width: "45%",
    marginTop: 6,
  },
});

export default styles;
