import { StyleSheet, Platform } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logoText: {
    fontSize: 20,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  editButton: {
    backgroundColor: "#0B132B",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 6,
  },
  editText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: 1,
    marginBottom: 16,
    fontFamily: fontBoldPlatform,
  },
  scoreBoardCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
  },
  teamBlock: {
    alignItems: "center",
  },
  teamIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  teamName: {
    fontSize: 16,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: 1,
    fontFamily: fontBoldPlatform,
  },
  teamSubtext: {
    fontSize: 9,
    fontWeight: "800",
    color: "#94A3B8",
    letterSpacing: 1,
    marginTop: 2,
  },
  vsScoreRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginVertical: 14,
  },
  scoreTextLarge: {
    fontSize: 42,
    fontWeight: "900",
    color: "#0F172A",
    fontFamily: fontBoldPlatform,
  },
  vsText: {
    fontSize: 16,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 2,
  },
  statusSubline: {
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    width: "100%",
    paddingTop: 14,
    marginTop: 8,
    alignItems: "center",
  },
  statusLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#94A3B8",
    letterSpacing: 1,
  },
  statusValue: {
    fontSize: 13,
    fontWeight: "900",
    color: "#0F172A",
    marginTop: 2,
    fontFamily: fontBoldPlatform,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#0F172A",
    marginBottom: 12,
    fontFamily: fontBoldPlatform,
  },
  tableCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#0B132B",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  colNameHeader: {
    flex: 1,
    fontSize: 11,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  colStatHeader: {
    width: 48,
    fontSize: 11,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1,
    textAlign: "center",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  nameText: {
    flex: 1,
    fontSize: 13,
    fontWeight: "900",
    color: "#0F172A",
    fontFamily: fontBoldPlatform,
  },
  statValueText: {
    width: 48,
    fontSize: 13,
    fontWeight: "600",
    color: "#0F172A",
    textAlign: "center",
  },
  coachNotesCard: {
    backgroundColor: "#0B132B",
    borderRadius: 14,
    padding: 20,
  },
  coachNotesTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1.5,
    marginBottom: 14,
  },
  noteRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  noteIndex: {
    fontSize: 13,
    fontWeight: "900",
    color: "#FFFFFF",
    marginRight: 12,
    fontFamily: fontBoldPlatform,
  },
  noteContentText: {
    flex: 1,
    fontSize: 13,
    color: "#E2E8F0",
    lineHeight: 18,
  },
  noteSkeleton1: {
    height: 8,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 4,
    width: "85%",
    marginTop: 4,
  },
  noteSkeleton2: {
    height: 8,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 4,
    width: "45%",
    marginTop: 6,
  },
});

export default styles;
