import { StyleSheet, Platform } from "react-native";

const fontPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

const fontBoldPlatform = Platform.select({
  ios: "System",
  android: "sans-serif-medium",
  default: "sans-serif",
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070D19",
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: "#070D19",
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logoText: {
    fontSize: 20,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 2,
    fontFamily: fontBoldPlatform,
  },
  editButton: {
    backgroundColor: "rgba(0, 200, 255, 0.12)",
    borderWidth: 1,
    borderColor: "#00C8FF",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 6,
  },
  editText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#00C8FF",
    letterSpacing: 0.5,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#F8FAFC",
    letterSpacing: 1,
    marginBottom: 16,
    fontFamily: fontBoldPlatform,
  },
  eventCard: {
    backgroundColor: "#0D1526",
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  tuneUpText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#00C8FF",
    letterSpacing: 1,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  eventTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#F8FAFC",
    fontFamily: fontBoldPlatform,
    marginBottom: 12,
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
    marginBottom: 14,
  },
  eventDateText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#94A3B8",
  },
  badgesRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  badgeCol: {
    alignItems: "center",
  },
  badgeLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#64748B",
    letterSpacing: 1,
  },
  badgeValue: {
    fontSize: 15,
    fontWeight: "900",
    color: "#00C8FF",
    marginTop: 2,
    fontFamily: fontBoldPlatform,
  },
  badgeDivider: {
    width: 1,
    height: 24,
    backgroundColor: "#1E293B",
  },
  tableCard: {
    backgroundColor: "#0D1526",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#111C33",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  colRank: {
    width: 50,
    fontSize: 11,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 0.5,
  },
  colName: {
    flex: 1,
    fontSize: 11,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 0.5,
  },
  colTime: {
    width: 70,
    fontSize: 11,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 0.5,
    textAlign: "right",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  rankSquareDark: {
    width: 34,
    height: 34,
    backgroundColor: "rgba(0, 200, 255, 0.15)",
    borderWidth: 1,
    borderColor: "#00C8FF",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  rankTextWhite: {
    fontSize: 15,
    fontWeight: "900",
    color: "#00C8FF",
    fontFamily: fontBoldPlatform,
  },
  rankSquareOutline: {
    width: 34,
    height: 34,
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: "#1E293B",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  rankTextDark: {
    fontSize: 15,
    fontWeight: "900",
    color: "#94A3B8",
    fontFamily: fontBoldPlatform,
  },
  nameContainer: {
    flex: 1,
  },
  nameText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#F8FAFC",
    fontFamily: fontBoldPlatform,
  },
  detailText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#94A3B8",
    marginTop: 2,
    letterSpacing: 0.5,
  },
  timeText: {
    fontSize: 16,
    fontWeight: "900",
    color: "#38BDF8",
    textAlign: "right",
    fontFamily: fontBoldPlatform,
  },
  coachNotesCard: {
    backgroundColor: "#0D1526",
    borderRadius: 14,
    padding: 20,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  coachNotesTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 1.5,
    marginBottom: 14,
  },
  noteRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  noteIndex: {
    fontSize: 13,
    fontWeight: "900",
    color: "#00C8FF",
    marginRight: 12,
    fontFamily: fontBoldPlatform,
  },
  noteContentText: {
    flex: 1,
    fontSize: 13,
    color: "#E2E8F0",
    lineHeight: 18,
  },
  noteSkeleton1: {
    height: 8,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 4,
    width: "85%",
    marginTop: 4,
  },
  noteSkeleton2: {
    height: 8,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 4,
    width: "45%",
    marginTop: 6,
  },
});

export default styles;
