import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0B132B",
  },
  headerBar: {
    paddingTop: 60,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: "#0B132B",
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  backButton: {
    padding: 4,
    marginRight: 16,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  profileHeaderBlock: {
    alignItems: "center",
    marginBottom: 20,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 16,
  },
  avatarBox: {
    width: 96,
    height: 96,
    borderRadius: 20,
    backgroundColor: "#111C35",
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  verifiedBadge: {
    position: "absolute",
    bottom: -4,
    right: -4,
    backgroundColor: "#0B132B",
    borderRadius: 12,
  },
  coachName: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  institutionRole: {
    color: "#94A3B8",
    fontSize: 12,
    textAlign: "center",
    marginBottom: 14,
  },
  tagsRow: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  tagPill: {
    backgroundColor: "#111C35",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginHorizontal: 3,
    marginBottom: 6,
  },
  tagPillActive: {
    backgroundColor: "#0284C7",
    borderColor: "#38BDF8",
  },
  tagText: {
    color: "#94A3B8",
    fontSize: 10,
    fontWeight: "800",
  },
  tagTextActive: {
    color: "#FFFFFF",
  },
  metricCardStack: {
    marginBottom: 20,
  },
  metricCardCenter: {
    backgroundColor: "#111C35",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 16,
    alignItems: "center",
    marginBottom: 12,
  },
  metricCard: {
    backgroundColor: "#111C35",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 16,
    marginBottom: 12,
  },
  metricCardLabel: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 8,
  },
  metricBigValue: {
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "900",
    marginVertical: 2,
  },
  metricSubtext: {
    color: "#64748B",
    fontSize: 12,
  },
  specialtiesList: {
    marginTop: 4,
  },
  specialtyItemCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0F172A",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 6,
  },
  specialtyIcon: {
    marginRight: 10,
  },
  specialtyText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  philosophySection: {
    marginBottom: 20,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  verticalAccentBar: {
    width: 3,
    height: 16,
    backgroundColor: "#38BDF8",
    marginRight: 8,
    borderRadius: 2,
  },
  sectionTitleText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  philosophyParagraph: {
    color: "#94A3B8",
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 12,
  },
  quoteCard: {
    backgroundColor: "#111C35",
    borderLeftWidth: 3,
    borderLeftColor: "#38BDF8",
    borderRadius: 8,
    padding: 14,
  },
  quoteText: {
    color: "#E2E8F0",
    fontSize: 12,
    fontStyle: "italic",
    lineHeight: 18,
  },
  certificatesCard: {
    backgroundColor: "#111C35",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 16,
    marginBottom: 20,
  },
  certBox: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 6,
  },
  certText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  contactCard: {
    backgroundColor: "#111C35",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
    padding: 16,
    marginBottom: 24,
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  contactText: {
    color: "#FFFFFF",
    fontSize: 13,
    marginLeft: 10,
  },
  sendInquiryButton: {
    backgroundColor: "#00A3FF",
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  sendIcon: {
    marginRight: 8,
  },
  sendInquiryText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.8,
  },

  /* MODAL STYLES (Screen 4) */
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#10B981",
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 8,
  },
  modalSubtitle: {
    color: "#FFFFFF",
    fontSize: 13,
    opacity: 0.9,
    textAlign: "center",
    marginBottom: 20,
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  modalButton: {
    flex: 0.48,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  modalButtonText: {
    color: "#10B981",
    fontSize: 13,
    fontWeight: "800",
  },
});

export default styles;
