import { StyleSheet, Platform } from 'react-native';

const fontBold = Platform.select({
  ios: 'System',
  android: 'sans-serif-black',
  default: 'sans-serif',
});

const fontMedium = Platform.select({
  ios: 'System',
  android: 'sans-serif-medium',
  default: 'sans-serif',
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#070D19',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
    backgroundColor: '#070D19',
  },
  backButton: {
    padding: 6,
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: fontBold,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
  },

  // Section Titles
  sectionLabel: {
    fontSize: 12,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 10,
    marginTop: 6,
  },

  // Active Selection Card
  activeCard: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 18,
    marginBottom: 24,
  },
  activeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  matchHeadline: {
    fontSize: 22,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  matchIdSubtext: {
    fontSize: 13,
    fontFamily: fontMedium,
    color: '#94A3B8',
    marginTop: 4,
  },
  divider: {
    height: 1,
    backgroundColor: '#1E293B',
    marginVertical: 16,
  },
  subGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  subGridCol: {
    flex: 1,
  },
  gridLabel: {
    fontSize: 11,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  gridValue: {
    fontSize: 15,
    fontFamily: fontBold,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 4,
  },

  // Request Status Card
  statusCard: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  statusIconBox: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#162032',
    borderWidth: 1,
    borderColor: '#1E293B',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  statusTitle: {
    fontSize: 18,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  statusSubtext: {
    fontSize: 13,
    fontFamily: fontMedium,
    color: '#94A3B8',
    marginTop: 4,
    lineHeight: 18,
    paddingRight: 12,
  },

  // Info Alert Box
  alertCard: {
    backgroundColor: '#0F172A',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 16,
    paddingLeft: 20,
    marginBottom: 28,
    position: 'relative',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  alertAccentBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: '#00C8FF',
  },
  alertIconContainer: {
    marginRight: 12,
    marginTop: 2,
  },
  alertText: {
    flex: 1,
    fontSize: 13,
    fontFamily: fontMedium,
    color: '#94A3B8',
    lineHeight: 20,
  },
  boldHighlight: {
    color: '#FFFFFF',
    fontFamily: fontBold,
    fontWeight: '700',
  },

  // Certification Banner Badge
  certifiedBanner: {
    backgroundColor: '#D1FAE5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  certifiedText: {
    fontSize: 14,
    fontFamily: fontBold,
    fontWeight: '900',
    color: '#059669',
    letterSpacing: 1,
    marginLeft: 8,
  },

  // Certified Match Score Card
  certifiedCard: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 20,
    marginBottom: 20,
  },
  sportTag: {
    fontSize: 12,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#00C8FF',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  dateText: {
    fontSize: 13,
    fontFamily: fontMedium,
    color: '#94A3B8',
    marginLeft: 6,
  },

  // Head-to-Head Big Score Tile
  scoreTile: {
    backgroundColor: '#070D19',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 20,
    marginTop: 18,
    position: 'relative',
  },
  homeTeamLabel: {
    fontSize: 11,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  awayTeamLabel: {
    fontSize: 11,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1,
    textTransform: 'uppercase',
    alignSelf: 'flex-end',
    marginTop: 4,
  },
  scoresRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  scoreNumber: {
    fontSize: 48,
    fontFamily: fontBold,
    fontWeight: '900',
    color: '#FFFFFF',
    marginHorizontal: 24,
  },
  scoreDivider: {
    width: 1,
    height: 44,
    backgroundColor: '#1E293B',
  },

  // Team Performance Statistics Table Section
  statsCard: {
    backgroundColor: '#0F172A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1E293B',
    padding: 18,
    marginBottom: 24,
  },
  statsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  statsTitleContainer: {
    flex: 1,
    paddingRight: 10,
  },
  statsTitle: {
    fontSize: 14,
    fontFamily: fontBold,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  statsTeamLabel: {
    fontSize: 10,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#00C8FF',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    textAlign: 'right',
    lineHeight: 14,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#0B132B',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  thText: {
    fontSize: 11,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  tdName: {
    fontSize: 14,
    fontFamily: fontBold,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  tdStat: {
    fontSize: 14,
    fontFamily: fontMedium,
    color: '#FFFFFF',
    textAlign: 'center',
  },

  // Bottom Primary Action Buttons
  primaryButton: {
    backgroundColor: '#2563EB',
    borderRadius: 12,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  disabledButton: {
    backgroundColor: '#1E293B',
  },
  primaryButtonText: {
    fontSize: 16,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#FFFFFF',
    marginLeft: 10,
    letterSpacing: 0.3,
  },
  demoToggleBtn: {
    marginTop: 14,
    padding: 10,
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: 'rgba(30, 41, 59, 0.5)',
  },
  demoToggleText: {
    fontSize: 12,
    fontFamily: fontMedium,
    color: '#00C8FF',
  },

  // Interruption Modal Dialog
  interruptionOverlay: {
    flex: 1,
    backgroundColor: 'rgba(7, 13, 25, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  interruptionCard: {
    width: '100%',
    backgroundColor: '#0F172A',
    borderColor: '#1E293B',
    borderWidth: 1,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#00C8FF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 12,
  },
  interruptionTitle: {
    fontSize: 20,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  fileNameBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#070D19',
    borderColor: '#1E293B',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    width: '100%',
    marginBottom: 20,
  },
  fileNameText: {
    flex: 1,
    fontSize: 13,
    fontFamily: fontMedium,
    color: '#00C8FF',
  },
  doneButton: {
    width: '100%',
    backgroundColor: '#2563EB',
    borderRadius: 12,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneButtonText: {
    fontSize: 15,
    fontFamily: fontBold,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
});

export default styles;
