import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  header: {
    height: '58px',
    backgroundColor: '#FFFFFF',
    borderBottom: '1px solid #0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 28px',
    boxSizing: 'border-box',
    flexShrink: 0,
    position: 'relative',
    zIndex: 50,
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  logo: {
    fontSize: '22px',
    fontWeight: 900,
    letterSpacing: '0.25em',
    color: '#0B132B',
    textDecoration: 'none',
  },
  logoSup: {
    fontSize: '10px',
    fontWeight: 800,
    verticalAlign: 'super',
    marginLeft: '3px',
    letterSpacing: '0.05em',
  },
  rightSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    position: 'relative',
  },
  bellBtn: {
    position: 'relative',
    backgroundColor: 'transparent',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    color: '#0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px',
    outline: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    transition: 'all 0.15s ease',
  },
  bellBtnHovered: {
    backgroundColor: '#F1F5F9',
    color: '#0284C7',
  },
  bellDot: {
    position: 'absolute',
    top: '4px',
    right: '4px',
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#EF4444',
    pointerEvents: 'none',
  },
  divider: {
    width: '1px',
    height: '26px',
    backgroundColor: '#CBD5E1',
  },
  profileLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    textDecoration: 'none',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '6px',
    transition: 'all 0.15s ease',
  },
  profileLinkHovered: {
    backgroundColor: '#F1F5F9',
  },
  profileCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  profileRole: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#94A3B8',
    letterSpacing: '0.12em',
    lineHeight: 1,
  },
  profileName: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.04em',
    marginTop: '3px',
    transition: 'color 0.15s ease',
  },
  profileNameHovered: {
    color: '#0284C7',
  },
  avatarWrap: {
    width: '32px',
    height: '32px',
    color: '#0B132B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    overflow: 'hidden',
    flexShrink: 0,
    transition: 'color 0.15s ease, transform 0.15s ease',
  },
  avatarWrapHovered: {
    color: '#0284C7',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  avatarIcon: {
    width: '28px',
    height: '28px',
  },
};
