import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  sidebar: {
    width: '240px',
    backgroundColor: '#FFFFFF',
    borderRight: '1px solid #0B132B',
    padding: '24px 16px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    flexShrink: 0,
    boxSizing: 'border-box',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  topSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  createBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '12px 20px',
    borderRadius: '16px',
    fontSize: '13px',
    fontWeight: 600,
    letterSpacing: '0.12em',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    width: '100%',
    boxSizing: 'border-box',
    transition: 'background-color 0.15s ease',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  navLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 14px',
    borderRadius: '4px',
    fontSize: '13px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textDecoration: 'none',
    color: '#64748B',
    backgroundColor: 'transparent',
    borderLeft: '4px solid transparent',
    transition: 'all 0.18s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  navLinkActive: {
    color: '#0284C7',
    backgroundColor: '#F0F9FF',
    borderLeft: '4px solid #0284C7',
  },
  navLinkHovered: {
    color: '#0B132B',
    backgroundColor: '#F1F5F9',
    borderLeft: '4px solid #CBD5E1',
  },
  logoutBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 14px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    color: '#EF4444',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    transition: 'all 0.18s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  logoutBtnHovered: {
    color: '#DC2626',
    backgroundColor: '#FEF2F2',
  },

  /* Modals Overlay & Boxes */
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    width: '92%',
    maxWidth: '500px',
    padding: '28px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
    boxSizing: 'border-box',
  },
  modalHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#64748B',
    padding: 0,
  },
  errorBox: {
    padding: '8px 12px',
    backgroundColor: '#FEF2F2',
    border: '1px solid #FECACA',
    borderRadius: '4px',
    color: '#B91C1C',
    fontSize: '12px',
    marginBottom: '14px',
  },
  formGroup: {
    marginBottom: '14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  formLabel: {
    fontSize: '11px',
    fontWeight: 800,
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  formInput: {
    border: '1px solid #CBD5E1',
    borderRadius: '4px',
    padding: '10px 12px',
    fontSize: '13px',
    outline: 'none',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    marginBottom: '14px',
  },
  formDivider: {
    borderTop: '1px dashed #CBD5E1',
    margin: '16px 0 14px 0',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    marginTop: '6px',
  },
  cancelBtn: {
    padding: '10px 16px',
    border: '1px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#64748B',
    fontWeight: 700,
    borderRadius: '4px',
    cursor: 'pointer',
  },
  saveBtn: {
    padding: '10px 18px',
    border: 'none',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontWeight: 800,
    borderRadius: '4px',
    cursor: 'pointer',
  },

  /* Logout Confirmation Modal */
  logoutCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    width: '90%',
    maxWidth: '400px',
    padding: '24px 28px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
    boxSizing: 'border-box',
  },
  logoutTitle: {
    fontSize: '15px',
    fontWeight: 800,
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  logoutDesc: {
    fontSize: '13px',
    color: '#64748B',
    margin: '0 0 24px 0',
    lineHeight: 1.5,
    fontWeight: 500,
  },
  logoutCancelBtn: {
    padding: '9px 18px',
    border: '1px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#64748B',
    fontWeight: 800,
    fontSize: '11px',
    cursor: 'pointer',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  logoutConfirmBtn: {
    padding: '9px 20px',
    border: 'none',
    backgroundColor: '#DC2626',
    color: '#FFFFFF',
    fontWeight: 800,
    fontSize: '11px',
    cursor: 'pointer',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    transition: 'background-color 0.15s ease',
  },
};
