import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#0B132B',
  },
  layoutBody: {
    display: 'flex',
    flex: 1,
    height: 'calc(100vh - 58px)',
    overflow: 'hidden',
  },
  contentArea: {
    flex: 1,
    height: '100%',
    padding: '24px 40px 31px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    maxWidth: '1280px',
    boxSizing: 'border-box',
  },
  pageTitle: {
    fontSize: '26px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    color: '#0B132B',
    margin: '0 0 4px 0',
    textTransform: 'uppercase',
  },
  pageSubtitle: {
    fontSize: '12px',
    color: '#64748B',
    margin: '0 0 18px 0',
    fontWeight: 500,
  },
  sectionCard: {
    border: '2px solid #0B132B',
    boxShadow: '3px 3px 0px #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '16px 20px',
    marginBottom: '16px',
  },
  sectionHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '10px',
    borderBottom: '1.5px solid #0B132B',
    marginBottom: '14px',
  },
  sectionHeading: {
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  headerIcon: {
    width: 17,
    height: 17,
    color: '#0B132B',
  },
  formGrid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '14px',
    marginBottom: '10px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
    marginBottom: '10px',
  },
  fieldLabel: {
    fontSize: '10.5px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  input: {
    border: '1.5px solid #0B132B',
    padding: '8px 12px',
    fontSize: '12.5px',
    fontWeight: 500,
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    transition: 'border-color 0.15s ease',
  },
  select: {
    border: '1.5px solid #0B132B',
    padding: '8px 12px',
    fontSize: '12.5px',
    fontWeight: 600,
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  addCoachBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1.5px solid #0B132B',
    padding: '10px',
    backgroundColor: '#FFFFFF',
    cursor: 'pointer',
    gap: '8px',
    transition: 'background-color 0.15s ease',
  },
  addCoachLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  dropzoneContainer: {
    border: '2px dashed #0B132B',
    backgroundColor: '#FAFAFA',
    padding: '20px 16px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    textAlign: 'center',
    marginBottom: '10px',
    transition: 'background-color 0.15s ease',
  },
  dropzoneTitle: {
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: '8px 0 2px',
    textTransform: 'uppercase',
  },
  dropzoneHelper: {
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  alertBox: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    border: '1.5px solid #0B132B',
    padding: '10px 14px',
    backgroundColor: '#FFFFFF',
  },
  alertText: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#0B132B',
    lineHeight: 1.45,
    margin: 0,
    letterSpacing: '0.02em',
  },
  footerActionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '18px',
  },
  cancelBtn: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    padding: '9px 22px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  createMatchBtn: {
    border: 'none',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '9px 24px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'opacity 0.15s ease',
  },
  errorNotice: {
    padding: '10px 14px',
    backgroundColor: '#FEF2F2',
    border: '1.5px solid #EF4444',
    color: '#DC2626',
    fontSize: '12px',
    fontWeight: 700,
    marginBottom: '12px',
  },
  successNotice: {
    padding: '10px 14px',
    backgroundColor: '#ECFDF5',
    border: '1.5px solid #10B981',
    color: '#059669',
    fontSize: '12px',
    fontWeight: 700,
    marginBottom: '12px',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '20px',
    backdropFilter: 'blur(3px)',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    padding: '28px 24px',
    maxWidth: '520px',
    width: '100%',
    textAlign: 'center',
    boxShadow: '0 20px 40px rgba(0,0,0,0.2)',
  },
  modalTitle: {
    fontSize: '20px',
    fontWeight: 900,
    color: '#0B132B',
    margin: '12px 0 6px',
    textTransform: 'uppercase',
    letterSpacing: '-0.01em',
  },
  modalSubtitle: {
    fontSize: '12.5px',
    color: '#64748B',
    margin: '0 0 18px',
    lineHeight: 1.5,
  },
  modalSummaryBox: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#F8FAFC',
    padding: '12px 16px',
    textAlign: 'left',
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  modalSummaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: '#0B132B',
  },
  modalActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  modalPrimaryBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    border: 'none',
    padding: '11px 18px',
    fontSize: '11.5px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    transition: 'opacity 0.15s ease',
  },
  modalSecondaryBtn: {
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    border: '2px solid #0B132B',
    padding: '10px 18px',
    fontSize: '11.5px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    width: '100%',
    transition: 'background-color 0.15s ease',
  },
  tableSection: {
    marginBottom: '14px',
  },
  tableSectionTitle: {
    fontSize: '12px',
    fontWeight: 900,
    letterSpacing: '0.04em',
    color: '#0B132B',
    textTransform: 'uppercase',
    marginBottom: '8px',
  },
  statsTableFrame: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    overflowX: 'auto',
    marginBottom: '10px',
  },
  statsTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '11.5px',
    textAlign: 'center',
  },
  statTh: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '8px 6px',
    fontSize: '10.5px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    borderRight: '1px solid #334155',
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
  },
  statTr: {
    borderBottom: '1px solid #E2E8F0',
  },
  statTd: {
    padding: '4px 6px',
    borderRight: '1px solid #E2E8F0',
    color: '#0B132B',
    fontWeight: 600,
  },
  statTdName: {
    textAlign: 'left',
    paddingLeft: '10px',
    fontWeight: 700,
  },
  statInput: {
    width: '100%',
    padding: '4px 3px',
    fontSize: '11.5px',
    fontWeight: 700,
    textAlign: 'center',
    border: '1px solid #CBD5E1',
    backgroundColor: '#F8FAFC',
    color: '#0B132B',
    outline: 'none',
    boxSizing: 'border-box',
  },
  statInputName: {
    width: '100%',
    padding: '4px 6px',
    fontSize: '11.5px',
    fontWeight: 700,
    textAlign: 'left',
    border: '1px solid #CBD5E1',
    backgroundColor: '#F8FAFC',
    color: '#0B132B',
    outline: 'none',
    boxSizing: 'border-box',
  },
  statTotalsTr: {
    backgroundColor: '#F1F5F9',
    fontWeight: 900,
    borderTop: '2px solid #0B132B',
  },
  statTotalsTd: {
    padding: '8px 6px',
    borderRight: '1px solid #CBD5E1',
    color: '#0B132B',
    fontWeight: 900,
    fontSize: '11.5px',
  },
  addRowBtn: {
    border: '1.5px dashed #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    padding: '6px 14px',
    fontSize: '10.5px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    textTransform: 'uppercase',
    marginBottom: '10px',
  },
  removeRowBtn: {
    border: 'none',
    backgroundColor: 'transparent',
    color: '#EF4444',
    cursor: 'pointer',
    fontWeight: 800,
    fontSize: '11px',
    padding: '3px',
  },
};
