import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundColor: '#FFFFFF',
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#0B132B',
  },
  layoutBody: {
    display: 'flex',
    flex: 1,
    minHeight: 'calc(100vh - 65px)',
  },
  contentArea: {
    flex: 1,
    padding: '36px 48px 80px',
    backgroundColor: '#FFFFFF',
    overflowY: 'auto',
    maxWidth: '1280px',
  },
  pageTitle: {
    fontSize: '34px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    color: '#0B132B',
    margin: '0 0 6px 0',
    textTransform: 'uppercase',
  },
  pageSubtitle: {
    fontSize: '13px',
    color: '#64748B',
    margin: '0 0 32px 0',
    fontWeight: 500,
  },
  sectionCard: {
    border: '2px solid #0B132B',
    boxShadow: '4px 4px 0px #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '24px 28px',
    marginBottom: '28px',
  },
  sectionHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '16px',
    borderBottom: '1.5px solid #0B132B',
    marginBottom: '20px',
  },
  sectionHeading: {
    fontSize: '15px',
    fontWeight: 900,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  headerIcon: {
    width: 18,
    height: 18,
    color: '#0B132B',
  },
  formGrid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px',
    marginBottom: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginBottom: '16px',
  },
  fieldLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  input: {
    border: '1.5px solid #0B132B',
    padding: '12px 14px',
    fontSize: '13px',
    fontWeight: 500,
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    transition: 'border-color 0.15s ease',
  },
  select: {
    border: '1.5px solid #0B132B',
    padding: '12px 14px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  addCoachBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1.5px solid #0B132B',
    padding: '14px',
    backgroundColor: '#FFFFFF',
    cursor: 'pointer',
    gap: '8px',
    transition: 'background-color 0.15s ease',
  },
  addCoachLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  dropzoneContainer: {
    border: '2px dashed #0B132B',
    backgroundColor: '#FAFAFA',
    padding: '36px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    textAlign: 'center',
    marginBottom: '16px',
    transition: 'background-color 0.15s ease',
  },
  dropzoneTitle: {
    fontSize: '13px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: '12px 0 4px',
    textTransform: 'uppercase',
  },
  dropzoneHelper: {
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  alertBox: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    border: '1.5px solid #0B132B',
    padding: '14px 18px',
    backgroundColor: '#FFFFFF',
  },
  alertText: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#0B132B',
    lineHeight: 1.45,
    margin: 0,
    letterSpacing: '0.02em',
  },
  footerActionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '16px',
    marginTop: '32px',
  },
  cancelBtn: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    padding: '12px 28px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  createMatchBtn: {
    border: 'none',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    padding: '12px 32px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'opacity 0.15s ease',
  },
  errorNotice: {
    padding: '12px 16px',
    backgroundColor: '#FEF2F2',
    border: '1.5px solid #EF4444',
    color: '#DC2626',
    fontSize: '12px',
    fontWeight: 700,
    marginBottom: '20px',
  },
  successNotice: {
    padding: '12px 16px',
    backgroundColor: '#ECFDF5',
    border: '1.5px solid #10B981',
    color: '#059669',
    fontSize: '12px',
    fontWeight: 700,
    marginBottom: '20px',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '20px',
    backdropFilter: 'blur(3px)',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    padding: '36px 32px',
    maxWidth: '520px',
    width: '100%',
    textAlign: 'center',
    boxShadow: '0 20px 40px rgba(0,0,0,0.2)',
  },
  modalTitle: {
    fontSize: '22px',
    fontWeight: 900,
    color: '#0B132B',
    margin: '16px 0 8px',
    textTransform: 'uppercase',
    letterSpacing: '-0.01em',
  },
  modalSubtitle: {
    fontSize: '13px',
    color: '#64748B',
    margin: '0 0 24px',
    lineHeight: 1.5,
  },
  modalSummaryBox: {
    border: '1.5px solid #0B132B',
    backgroundColor: '#F8FAFC',
    padding: '16px 20px',
    textAlign: 'left',
    marginBottom: '28px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  modalSummaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: '#0B132B',
  },
  modalActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  modalPrimaryBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    border: 'none',
    padding: '13px 20px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    transition: 'opacity 0.15s ease',
  },
  modalSecondaryBtn: {
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    border: '2px solid #0B132B',
    padding: '11px 20px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    width: '100%',
    transition: 'background-color 0.15s ease',
  },
};
