import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    minHeight: '100vh',
    width: '100%',
    backgroundColor: '#FFFFFF',
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#0B132B',
    overflowY: 'auto',
  },
  contentArea: {
    maxWidth: '1540px',
    margin: '0 auto',
    padding: '36px 48px 80px',
    width: '100%',
    boxSizing: 'border-box',
  },
  topReturnBar: {
    marginBottom: '20px',
  },
  returnBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 18px',
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    color: '#0B132B',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    textDecoration: 'none',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  matchHeaderCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '24px',
    border: '2px solid #0B132B',
    padding: '24px 32px',
    backgroundColor: '#FFFFFF',
    marginBottom: '32px',
  },
  headerLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  leagueCategory: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  matchupTitle: {
    fontSize: '32px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  matchDateTime: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#334155',
  },
  coachHeaderTag: {
    marginLeft: '12px',
    color: '#64748B',
    fontWeight: 600,
  },
  coachNameText: {
    color: '#0B132B',
  },
  certifiedHeaderBadge: {
    padding: '3px 8px',
    fontSize: '10px',
    fontWeight: 800,
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    marginLeft: '12px',
    letterSpacing: '0.04em',
  },
  scoreboardTile: {
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
    border: '1.5px solid #0B132B',
    padding: '12px 28px',
    backgroundColor: '#FFFFFF',
  },
  scoreTeamBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
  },
  scoreTeamLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  scoreValue: {
    fontSize: '36px',
    fontWeight: 900,
    color: '#0B132B',
    lineHeight: 1,
    margin: '2px 0 6px',
  },
  scoreDivider: {
    fontSize: '24px',
    fontWeight: 800,
    color: '#94A3B8',
    padding: '0 8px',
  },
  badgeWin: {
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    padding: '3px 10px',
    borderRadius: '3px',
    textTransform: 'uppercase',
  },
  badgeLose: {
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    padding: '3px 10px',
    borderRadius: '3px',
    textTransform: 'uppercase',
  },
  unplayedBadge: {
    backgroundColor: '#E2E8F0',
    color: '#64748B',
    border: '1px solid #CBD5E1',
    padding: '3px 8px',
    fontSize: '10px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  sportTitleVal: {
    fontSize: '20px',
    fontWeight: 900,
    textTransform: 'uppercase',
    color: '#0B132B',
  },
  tableSection: {
    marginBottom: '32px',
  },
  tableHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  tableSectionTitle: {
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
    paddingBottom: '8px',
    borderBottom: '2.5px solid #0B132B',
    marginBottom: '16px',
    display: 'inline-block',
  },
  editToggleBtn: {
    padding: '6px 14px',
    fontSize: '11px',
    fontWeight: 700,
    border: '1px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    cursor: 'pointer',
    marginLeft: '12px',
    textTransform: 'uppercase',
  },
  statsTableFrame: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    overflowX: 'auto',
  },
  statsTable: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'center',
  },
  statTh: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    padding: '10px 8px',
    borderRight: '1px solid #1E293B',
    whiteSpace: 'nowrap',
  },
  statThNo: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    padding: '10px 8px',
    borderRight: '1px solid #1E293B',
    whiteSpace: 'nowrap',
    width: '48px',
  },
  statThRank: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    padding: '10px 8px',
    borderRight: '1px solid #1E293B',
    whiteSpace: 'nowrap',
    width: '60px',
  },
  statThPlayerName: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    padding: '10px 8px',
    borderRight: '1px solid #1E293B',
    whiteSpace: 'nowrap',
    textAlign: 'left',
    paddingLeft: '14px',
  },
  statThLast: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    padding: '10px 8px',
    borderRight: 'none',
    whiteSpace: 'nowrap',
  },
  statTr: {
    borderBottom: '1px solid #0B132B',
  },
  statTd: {
    padding: '10px 8px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#0B132B',
    borderRight: '1px solid #0B132B',
    verticalAlign: 'middle',
  },
  statTdName: {
    padding: '10px 8px',
    fontSize: '12px',
    color: '#0B132B',
    borderRight: '1px solid #0B132B',
    verticalAlign: 'middle',
    textAlign: 'left',
    paddingLeft: '14px',
    fontWeight: 700,
  },
  statTdBold: {
    padding: '10px 8px',
    fontSize: '12px',
    fontWeight: 800,
    color: '#0B132B',
    borderRight: '1px solid #0B132B',
    verticalAlign: 'middle',
  },
  statTdLast: {
    padding: '10px 8px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#0B132B',
    borderRight: 'none',
    verticalAlign: 'middle',
  },
  statInput: {
    width: '100%',
    maxWidth: '60px',
    textAlign: 'center',
    border: '1px solid #CBD5E1',
    borderRadius: '2px',
    padding: '3px 4px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#0B132B',
    backgroundColor: '#F8FAFC',
    outline: 'none',
  },
  statInputName: {
    width: '100%',
    border: '1px solid #CBD5E1',
    borderRadius: '2px',
    padding: '3px 6px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#0B132B',
    backgroundColor: '#F8FAFC',
    outline: 'none',
  },
  statTotalsTr: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
  },
  statTotalsTd: {
    padding: '12px 8px',
    fontSize: '11px',
    fontWeight: 800,
    color: '#FFFFFF',
    borderRight: '1px solid #1E293B',
    letterSpacing: '0.03em',
  },
  statTotalsTdName: {
    padding: '12px 8px',
    fontSize: '11px',
    fontWeight: 800,
    color: '#FFFFFF',
    borderRight: '1px solid #1E293B',
    letterSpacing: '0.03em',
    textAlign: 'left',
    paddingLeft: '14px',
  },
  statTotalsTdLast: {
    padding: '12px 8px',
    fontSize: '11px',
    fontWeight: 800,
    color: '#FFFFFF',
    borderRight: 'none',
    letterSpacing: '0.03em',
  },
  tableEmptyNotice: {
    padding: '24px',
    color: '#64748B',
    textAlign: 'center',
  },
  statusDq: {
    color: '#EF4444',
    fontWeight: 800,
  },
  statusOfficial: {
    color: '#10B981',
    fontWeight: 800,
  },
  addPlayerBtnRow: {
    display: 'flex',
    justifyContent: 'flex-start',
    marginTop: '10px',
  },
  addPlayerBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    fontSize: '11px',
    fontWeight: 800,
    border: '1.5px dashed #0B132B',
    backgroundColor: '#F8FAFC',
    color: '#0B132B',
    cursor: 'pointer',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    transition: 'all 0.15s ease',
  },
  removeRowBtn: {
    background: 'none',
    border: 'none',
    color: '#EF4444',
    cursor: 'pointer',
    padding: '4px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '2px',
  },
  bottomGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '24px',
    marginBottom: '32px',
  },
  boxContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  boxLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  hiddenInput: {
    display: 'none',
  },
  dropzone: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px dashed #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '32px 20px',
    minHeight: '160px',
    cursor: 'pointer',
    textAlign: 'center',
    transition: 'all 0.15s ease',
  },
  dropzoneText: {
    fontSize: '13px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: '10px 0 4px',
    textTransform: 'uppercase',
  },
  dropzoneSubtext: {
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  scoresheetPreviewTile: {
    backgroundColor: '#F8FAFC',
    borderColor: '#0B132B',
    borderStyle: 'solid',
    borderWidth: '1.5px',
    padding: '10px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '160px',
    height: '100%',
    overflow: 'hidden',
    position: 'relative',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
  },
  scoresheetPdfBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    padding: '16px',
  },
  scoresheetPdfTitle: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.04em',
  },
  scoresheetPdfHint: {
    fontSize: '11px',
    color: '#64748B',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  scoresheetImgWrap: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  scoresheetThumb: {
    maxWidth: '100%',
    maxHeight: '175px',
    width: 'auto',
    height: 'auto',
    objectFit: 'contain',
    borderRadius: '3px',
    display: 'block',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
    transition: 'transform 0.2s ease',
  },
  scoresheetEnlargeBadge: {
    marginTop: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    padding: '4px 10px',
    borderRadius: '3px',
  },
  replaceScoresheetBtn: {
    marginTop: '8px',
    padding: '4px 12px',
    fontSize: '10px',
    fontWeight: 800,
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    border: '1px solid #CBD5E1',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  bentoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
    gap: '10px',
    width: '100%',
    marginBottom: '10px',
  },
  bentoCard: {
    border: '1.5px solid #0B132B',
    boxShadow: '2px 2px 0px #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '8px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    borderRadius: '4px',
    boxSizing: 'border-box',
  },
  bentoHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: '6px',
    paddingBottom: '4px',
    borderBottom: '1px solid #E2E8F0',
  },
  bentoBadge: {
    fontSize: '10px',
    fontWeight: 800,
    color: '#0B132B',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  bentoDeleteBtn: {
    border: 'none',
    backgroundColor: '#FEF2F2',
    color: '#EF4444',
    borderRadius: '3px',
    padding: '2px 5px',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    fontSize: '9.5px',
    fontWeight: 700,
  },
  bentoThumb: {
    width: '100%',
    height: '130px',
    objectFit: 'contain',
    backgroundColor: '#F8FAFC',
    borderRadius: '2px',
    border: '1px solid #E2E8F0',
    display: 'block',
  },
  bentoFileName: {
    fontSize: '9.5px',
    fontWeight: 700,
    color: '#64748B',
    marginTop: '4px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    width: '100%',
  },
  actionToolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    justifyContent: 'center',
    marginTop: '8px',
  },
  actionBtnPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '6px 12px',
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    border: '1px solid #0B132B',
    borderRadius: '4px',
    fontSize: '10.5px',
    fontWeight: 800,
    cursor: 'pointer',
    letterSpacing: '0.04em',
  },
  actionBtnOutline: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '6px 12px',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    border: '1.5px solid #0B132B',
    borderRadius: '4px',
    fontSize: '10.5px',
    fontWeight: 800,
    cursor: 'pointer',
    letterSpacing: '0.04em',
  },
  actionBtnDanger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '6px 12px',
    backgroundColor: '#FEF2F2',
    color: '#EF4444',
    border: '1px solid #FCA5A5',
    borderRadius: '4px',
    fontSize: '10.5px',
    fontWeight: 800,
    cursor: 'pointer',
    letterSpacing: '0.04em',
  },
  noScoresheetCertifiedBox: {
    backgroundColor: '#F8FAFC',
    borderStyle: 'solid',
    border: '1.5px solid #CBD5E1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
    padding: '20px',
  },
  noScoresheetTitle: {
    fontSize: '12px',
    fontWeight: 800,
    color: '#64748B',
  },
  noScoresheetSubtitle: {
    fontSize: '11px',
    color: '#94A3B8',
  },
  uploadErrorNotice: {
    fontSize: '12px',
    color: '#EF4444',
    fontWeight: 600,
  },
  notesTextarea: {
    width: '100%',
    minHeight: '160px',
    border: '1.5px solid #0B132B',
    padding: '14px 16px',
    fontSize: '13px',
    fontFamily: 'inherit',
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    resize: 'vertical',
  },
  actionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '16px',
    paddingTop: '16px',
  },
  actionsRightGroup: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  removeBtn: {
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 28px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  certifyBtn: {
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 28px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  certifyBtnDisabled: {
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 28px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    borderRadius: '4px',
    opacity: 0.7,
    cursor: 'default',
  },
  downloadBtn: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 24px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    borderRadius: '4px',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.15s ease',
  },
  actionErrorNotice: {
    fontSize: '12px',
    color: '#EF4444',
    fontWeight: 600,
  },
  loadingContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 'calc(100vh - 200px)',
  },
  emptyNoticeText: {
    padding: '60px 0',
    textAlign: 'center',
    color: '#64748B',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '20px',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    maxWidth: '460px',
    width: '100%',
    padding: '28px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.2)',
  },
  modalHeaderWithIcon: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  modalDesc: {
    fontSize: '13px',
    color: '#475569',
    lineHeight: 1.5,
    margin: 0,
  },
  modalActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '8px',
  },
  modalCancelBtn: {
    padding: '8px 18px',
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    fontSize: '12px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  modalConfirmBtnRed: {
    padding: '8px 20px',
    border: 'none',
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    fontSize: '12px',
    fontWeight: 800,
    cursor: 'pointer',
  },
  modalConfirmBtnGreen: {
    padding: '8px 20px',
    border: 'none',
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    fontSize: '12px',
    fontWeight: 800,
    cursor: 'pointer',
  },
  previewModalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    width: '100%',
    maxWidth: '780px',
    maxHeight: '90vh',
    padding: '20px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.2)',
    overflowY: 'auto',
  },
  previewModalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  closeXBtn: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: '#64748B',
  },
  previewPdfIframe: {
    width: '100%',
    height: '500px',
    border: '1px solid #CBD5E1',
  },
  previewImg: {
    width: '100%',
    maxHeight: '68vh',
    objectFit: 'contain',
    border: '1px solid #CBD5E1',
    borderRadius: '4px',
    display: 'block',
  },
  previewModalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '2px',
  },
};
