import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    minHeight: '100vh',
    width: '100%',
    backgroundColor: '#FFFFFF',
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#0B132B',
    overflowY: 'auto',
  },
  contentArea: {
    maxWidth: '1540px',
    margin: '0 auto',
    padding: '36px 48px 80px',
    width: '100%',
    boxSizing: 'border-box',
  },
  topReturnBar: {
    marginBottom: '20px',
  },
  returnBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 18px',
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    color: '#0B132B',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    textDecoration: 'none',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  matchHeaderCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '24px',
    border: '2px solid #0B132B',
    padding: '24px 32px',
    backgroundColor: '#FFFFFF',
    marginBottom: '32px',
  },
  headerLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  leagueCategory: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  matchupTitle: {
    fontSize: '32px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  matchDateTime: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#334155',
  },
  scoreboardTile: {
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
    border: '1.5px solid #0B132B',
    padding: '12px 28px',
    backgroundColor: '#FFFFFF',
  },
  scoreTeamBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
  },
  scoreTeamLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  scoreValue: {
    fontSize: '36px',
    fontWeight: 900,
    color: '#0B132B',
    lineHeight: 1,
    margin: '2px 0 6px',
  },
  scoreDivider: {
    fontSize: '24px',
    fontWeight: 800,
    color: '#94A3B8',
    padding: '0 8px',
  },
  badgeWin: {
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    padding: '3px 10px',
    borderRadius: '3px',
    textTransform: 'uppercase',
  },
  badgeLose: {
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    padding: '3px 10px',
    borderRadius: '3px',
    textTransform: 'uppercase',
  },
  tableSection: {
    marginBottom: '32px',
  },
  tableSectionTitle: {
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
    paddingBottom: '8px',
    borderBottom: '2.5px solid #0B132B',
    marginBottom: '16px',
    display: 'inline-block',
  },
  statsTableFrame: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    overflowX: 'auto',
  },
  statsTable: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'center',
  },
  statTh: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    padding: '10px 8px',
    borderRight: '1px solid #1E293B',
    whiteSpace: 'nowrap',
  },
  statTr: {
    borderBottom: '1px solid #0B132B',
  },
  statTd: {
    padding: '10px 8px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#0B132B',
    borderRight: '1px solid #0B132B',
    verticalAlign: 'middle',
  },
  statTdName: {
    textAlign: 'left',
    paddingLeft: '14px',
    fontWeight: 700,
  },
  statInput: {
    width: '100%',
    maxWidth: '60px',
    textAlign: 'center',
    border: '1px solid #CBD5E1',
    borderRadius: '2px',
    padding: '3px 4px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#0B132B',
    backgroundColor: '#F8FAFC',
    outline: 'none',
  },
  statInputName: {
    width: '100%',
    border: '1px solid #CBD5E1',
    borderRadius: '2px',
    padding: '3px 6px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#0B132B',
    backgroundColor: '#F8FAFC',
    outline: 'none',
  },
  statTotalsTr: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
  },
  statTotalsTd: {
    padding: '12px 8px',
    fontSize: '11px',
    fontWeight: 800,
    color: '#FFFFFF',
    borderRight: '1px solid #1E293B',
    letterSpacing: '0.03em',
  },
  bottomGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '24px',
    marginBottom: '32px',
  },
  boxContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  boxLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    color: '#0B132B',
    textTransform: 'uppercase',
  },
  dropzone: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px dashed #0B132B',
    backgroundColor: '#FFFFFF',
    padding: '32px 20px',
    minHeight: '160px',
    cursor: 'pointer',
    textAlign: 'center',
    transition: 'all 0.15s ease',
  },
  dropzoneText: {
    fontSize: '13px',
    fontWeight: 800,
    letterSpacing: '0.04em',
    color: '#0B132B',
    margin: '10px 0 4px',
    textTransform: 'uppercase',
  },
  dropzoneSubtext: {
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  scoresheetPreview: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: '1.5px solid #0B132B',
    padding: '12px 16px',
    backgroundColor: '#F8FAFC',
    marginTop: '10px',
  },
  notesTextarea: {
    width: '100%',
    minHeight: '160px',
    border: '1.5px solid #0B132B',
    padding: '14px 16px',
    fontSize: '13px',
    fontFamily: 'inherit',
    color: '#0B132B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    resize: 'vertical',
  },
  actionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '16px',
    paddingTop: '16px',
  },
  removeBtn: {
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 28px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  certifyBtn: {
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    border: 'none',
    padding: '12px 28px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 19, 43, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '20px',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: '2px solid #0B132B',
    maxWidth: '460px',
    width: '100%',
    padding: '28px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.2)',
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  modalDesc: {
    fontSize: '13px',
    color: '#475569',
    lineHeight: 1.5,
    margin: 0,
  },
  modalActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '8px',
  },
  modalCancelBtn: {
    padding: '8px 18px',
    border: '1.5px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    fontSize: '12px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  modalConfirmBtnRed: {
    padding: '8px 20px',
    border: 'none',
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    fontSize: '12px',
    fontWeight: 800,
    cursor: 'pointer',
  },
  modalConfirmBtnGreen: {
    padding: '8px 20px',
    border: 'none',
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    fontSize: '12px',
    fontWeight: 800,
    cursor: 'pointer',
  },
  editToggleBtn: {
    padding: '6px 14px',
    fontSize: '11px',
    fontWeight: 700,
    border: '1px solid #0B132B',
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
    cursor: 'pointer',
    marginLeft: '12px',
    textTransform: 'uppercase',
  },
};
