import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  shell: {
    minHeight: '100vh',
    width: '100%',
    backgroundColor: '#FFFFFF',
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#0B132B',
    overflowY: 'auto',
  },
  contentArea: {
    maxWidth: '1540px',
    margin: '0 auto',
    padding: '36px 48px 80px',
    width: '100%',
    boxSizing: 'border-box',
  },
  pageHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '28px',
  },
  pageTitle: {
    fontSize: '34px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    color: '#0B132B',
    margin: 0,
    textTransform: 'uppercase',
  },
  backLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '14px',
    fontWeight: 700,
    color: '#0B132B',
    textDecoration: 'none',
    cursor: 'pointer',
    transition: 'opacity 0.15s ease',
  },
  filterBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '16px',
    marginBottom: '28px',
  },
  tabGroup: {
    display: 'inline-flex',
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
  },
  tabBtn: {
    padding: '12px 28px',
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    outline: 'none',
  },
  tabBtnActive: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
  },
  tabBtnInactive: {
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
  },
  sportFilterWrap: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '10px',
  },
  sportFilterLabel: {
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  sportBtnGroup: {
    display: 'inline-flex',
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    flexWrap: 'wrap',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
  },
  sportBtn: {
    padding: '9px 16px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    border: 'none',
    borderRight: '1.5px solid #0B132B',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.15s ease',
    outline: 'none',
  },
  sportBtnActive: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
  },
  sportBtnInactive: {
    backgroundColor: '#FFFFFF',
    color: '#0B132B',
  },
  tableFrame: {
    border: '2px solid #0B132B',
    backgroundColor: '#FFFFFF',
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    backgroundColor: '#0B132B',
    color: '#FFFFFF',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    padding: '14px 18px',
    borderRight: '1px solid #1E293B',
    whiteSpace: 'nowrap',
  },
  tr: {
    borderBottom: '1.5px solid #0B132B',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  td: {
    padding: '16px 18px',
    fontSize: '13px',
    color: '#0B132B',
    borderRight: '1.5px solid #0B132B',
    verticalAlign: 'middle',
  },
  tdMatchId: {
    fontWeight: 800,
    letterSpacing: '0.02em',
    color: '#0B132B',
    whiteSpace: 'nowrap',
  },
  tdMatchClass: {
    fontWeight: 600,
    color: '#0F172A',
  },
  tdSport: {
    fontWeight: 500,
    color: '#334155',
  },
  tdCoaches: {
    fontWeight: 500,
    color: '#334155',
    lineHeight: 1.45,
    whiteSpace: 'pre-line',
  },
  tdDateTime: {
    fontWeight: 600,
    color: '#0F172A',
    whiteSpace: 'nowrap',
  },
  statusPending: {
    display: 'inline-block',
    border: '1.5px solid #F59E0B',
    backgroundColor: '#FFFBEB',
    color: '#D97706',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '6px 12px',
    borderRadius: '4px',
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
  },
  statusAudited: {
    display: 'inline-block',
    border: '1.5px solid #10B981',
    backgroundColor: '#ECFDF5',
    color: '#059669',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '0.06em',
    padding: '6px 12px',
    borderRadius: '4px',
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
  },
  skeletonRow: {
    height: '24px',
    backgroundColor: '#F1F5F9',
    borderRadius: '4px',
    animation: 'pulse 1.5s infinite',
  },
  emptyState: {
    padding: '48px 24px',
    textAlign: 'center',
    color: '#64748B',
    fontSize: '14px',
    fontWeight: 500,
  },
};
